// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/bigquery/datatransfer/v1/datasource.proto

package datatransfer // import "google.golang.org/genproto/googleapis/cloud/bigquery/datatransfer/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "google.golang.org/genproto/googleapis/cloud/bigquery/v2"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Data format.
type ImportedDataInfo_Format int32

const (
	// Unspecified format. In this case, we have to infer the format from the
	// data source.
	ImportedDataInfo_FORMAT_UNSPECIFIED ImportedDataInfo_Format = 0
	// CSV format.
	ImportedDataInfo_CSV ImportedDataInfo_Format = 1
	// Newline-delimited JSON.
	ImportedDataInfo_JSON ImportedDataInfo_Format = 2
	// Avro format. See http://avro.apache.org .
	ImportedDataInfo_AVRO ImportedDataInfo_Format = 3
	// RecordIO.
	ImportedDataInfo_RECORDIO ImportedDataInfo_Format = 4
	// ColumnIO.
	ImportedDataInfo_COLUMNIO ImportedDataInfo_Format = 5
	// Capacitor.
	ImportedDataInfo_CAPACITOR ImportedDataInfo_Format = 6
	// Parquet format. See https://parquet.apache.org .
	ImportedDataInfo_PARQUET ImportedDataInfo_Format = 7
	// ORC format. See https://orc.apache.org .
	ImportedDataInfo_ORC ImportedDataInfo_Format = 8
)

var ImportedDataInfo_Format_name = map[int32]string{
	0: "FORMAT_UNSPECIFIED",
	1: "CSV",
	2: "JSON",
	3: "AVRO",
	4: "RECORDIO",
	5: "COLUMNIO",
	6: "CAPACITOR",
	7: "PARQUET",
	8: "ORC",
}
var ImportedDataInfo_Format_value = map[string]int32{
	"FORMAT_UNSPECIFIED": 0,
	"CSV":                1,
	"JSON":               2,
	"AVRO":               3,
	"RECORDIO":           4,
	"COLUMNIO":           5,
	"CAPACITOR":          6,
	"PARQUET":            7,
	"ORC":                8,
}

func (x ImportedDataInfo_Format) String() string {
	return proto.EnumName(ImportedDataInfo_Format_name, int32(x))
}
func (ImportedDataInfo_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 0}
}

// Encoding of input data in CSV/JSON format.
type ImportedDataInfo_Encoding int32

const (
	// Default encoding (UTF8).
	ImportedDataInfo_ENCODING_UNSPECIFIED ImportedDataInfo_Encoding = 0
	// ISO_8859_1 encoding.
	ImportedDataInfo_ISO_8859_1 ImportedDataInfo_Encoding = 1
	// UTF8 encoding.
	ImportedDataInfo_UTF8 ImportedDataInfo_Encoding = 2
)

var ImportedDataInfo_Encoding_name = map[int32]string{
	0: "ENCODING_UNSPECIFIED",
	1: "ISO_8859_1",
	2: "UTF8",
}
var ImportedDataInfo_Encoding_value = map[string]int32{
	"ENCODING_UNSPECIFIED": 0,
	"ISO_8859_1":           1,
	"UTF8":                 2,
}

func (x ImportedDataInfo_Encoding) String() string {
	return proto.EnumName(ImportedDataInfo_Encoding_name, int32(x))
}
func (ImportedDataInfo_Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 1}
}

// LINT.IfChange
// Field type.
type ImportedDataInfo_FieldSchema_Type int32

const (
	// Illegal value.
	ImportedDataInfo_FieldSchema_TYPE_UNSPECIFIED ImportedDataInfo_FieldSchema_Type = 0
	// 64K, UTF8.
	ImportedDataInfo_FieldSchema_STRING ImportedDataInfo_FieldSchema_Type = 1
	// 64-bit signed.
	ImportedDataInfo_FieldSchema_INTEGER ImportedDataInfo_FieldSchema_Type = 2
	// 64-bit IEEE floating point.
	ImportedDataInfo_FieldSchema_FLOAT ImportedDataInfo_FieldSchema_Type = 3
	// Aggregate type.
	ImportedDataInfo_FieldSchema_RECORD ImportedDataInfo_FieldSchema_Type = 4
	// 64K, Binary.
	ImportedDataInfo_FieldSchema_BYTES ImportedDataInfo_FieldSchema_Type = 5
	// 2-valued.
	ImportedDataInfo_FieldSchema_BOOLEAN ImportedDataInfo_FieldSchema_Type = 6
	// 64-bit signed usec since UTC epoch.
	ImportedDataInfo_FieldSchema_TIMESTAMP ImportedDataInfo_FieldSchema_Type = 7
	// Civil date - Year, Month, Day.
	ImportedDataInfo_FieldSchema_DATE ImportedDataInfo_FieldSchema_Type = 8
	// Civil time - Hour, Minute, Second, Microseconds.
	ImportedDataInfo_FieldSchema_TIME ImportedDataInfo_FieldSchema_Type = 9
	// Combination of civil date and civil time.
	ImportedDataInfo_FieldSchema_DATETIME ImportedDataInfo_FieldSchema_Type = 10
	// Numeric type with 38 decimal digits of precision and 9 decimal digits
	// of scale.
	ImportedDataInfo_FieldSchema_NUMERIC ImportedDataInfo_FieldSchema_Type = 11
)

var ImportedDataInfo_FieldSchema_Type_name = map[int32]string{
	0:  "TYPE_UNSPECIFIED",
	1:  "STRING",
	2:  "INTEGER",
	3:  "FLOAT",
	4:  "RECORD",
	5:  "BYTES",
	6:  "BOOLEAN",
	7:  "TIMESTAMP",
	8:  "DATE",
	9:  "TIME",
	10: "DATETIME",
	11: "NUMERIC",
}
var ImportedDataInfo_FieldSchema_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"STRING":           1,
	"INTEGER":          2,
	"FLOAT":            3,
	"RECORD":           4,
	"BYTES":            5,
	"BOOLEAN":          6,
	"TIMESTAMP":        7,
	"DATE":             8,
	"TIME":             9,
	"DATETIME":         10,
	"NUMERIC":          11,
}

func (x ImportedDataInfo_FieldSchema_Type) String() string {
	return proto.EnumName(ImportedDataInfo_FieldSchema_Type_name, int32(x))
}
func (ImportedDataInfo_FieldSchema_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 0, 0}
}

// Describes data which should be imported.
type ImportedDataInfo struct {
	// SQL query to run. When empty, API checks that there is only one
	// table_def specified and loads this table. Only Standard SQL queries
	// are accepted. Legacy SQL is not allowed.
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	// Table where results should be written.
	DestinationTableId string `protobuf:"bytes,2,opt,name=destination_table_id,json=destinationTableId,proto3" json:"destination_table_id,omitempty"`
	// The description of a destination table. This can be several sentences
	// or paragraphs describing the table contents in detail.
	DestinationTableDescription string `protobuf:"bytes,10,opt,name=destination_table_description,json=destinationTableDescription,proto3" json:"destination_table_description,omitempty"`
	// When used WITHOUT the "sql" parameter, describes the schema of the
	// destination table.
	// When used WITH the "sql" parameter, describes tables with data stored
	// outside of BigQuery.
	TableDefs []*ImportedDataInfo_TableDefinition `protobuf:"bytes,3,rep,name=table_defs,json=tableDefs,proto3" json:"table_defs,omitempty"`
	// Inline code for User-defined function resources.
	// Ignored when "sql" parameter is empty.
	UserDefinedFunctions []string `protobuf:"bytes,4,rep,name=user_defined_functions,json=userDefinedFunctions,proto3" json:"user_defined_functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportedDataInfo) Reset()         { *m = ImportedDataInfo{} }
func (m *ImportedDataInfo) String() string { return proto.CompactTextString(m) }
func (*ImportedDataInfo) ProtoMessage()    {}
func (*ImportedDataInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0}
}
func (m *ImportedDataInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportedDataInfo.Unmarshal(m, b)
}
func (m *ImportedDataInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportedDataInfo.Marshal(b, m, deterministic)
}
func (dst *ImportedDataInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportedDataInfo.Merge(dst, src)
}
func (m *ImportedDataInfo) XXX_Size() int {
	return xxx_messageInfo_ImportedDataInfo.Size(m)
}
func (m *ImportedDataInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportedDataInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImportedDataInfo proto.InternalMessageInfo

func (m *ImportedDataInfo) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *ImportedDataInfo) GetDestinationTableId() string {
	if m != nil {
		return m.DestinationTableId
	}
	return ""
}

func (m *ImportedDataInfo) GetDestinationTableDescription() string {
	if m != nil {
		return m.DestinationTableDescription
	}
	return ""
}

func (m *ImportedDataInfo) GetTableDefs() []*ImportedDataInfo_TableDefinition {
	if m != nil {
		return m.TableDefs
	}
	return nil
}

func (m *ImportedDataInfo) GetUserDefinedFunctions() []string {
	if m != nil {
		return m.UserDefinedFunctions
	}
	return nil
}

// Defines schema of a field in the imported data.
type ImportedDataInfo_FieldSchema struct {
	// Field name. Matches: [A-Za-z_][A-Za-z_0-9]{0,127}
	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Field type
	Type ImportedDataInfo_FieldSchema_Type `protobuf:"varint,2,opt,name=type,proto3,enum=google.cloud.bigquery.datatransfer.v1.ImportedDataInfo_FieldSchema_Type" json:"type,omitempty"`
	// Is field repeated.
	IsRepeated bool `protobuf:"varint,3,opt,name=is_repeated,json=isRepeated,proto3" json:"is_repeated,omitempty"`
	// Description for this field.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Present iff type == RECORD.
	Schema               *ImportedDataInfo_RecordSchema `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ImportedDataInfo_FieldSchema) Reset()         { *m = ImportedDataInfo_FieldSchema{} }
func (m *ImportedDataInfo_FieldSchema) String() string { return proto.CompactTextString(m) }
func (*ImportedDataInfo_FieldSchema) ProtoMessage()    {}
func (*ImportedDataInfo_FieldSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 0}
}
func (m *ImportedDataInfo_FieldSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportedDataInfo_FieldSchema.Unmarshal(m, b)
}
func (m *ImportedDataInfo_FieldSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportedDataInfo_FieldSchema.Marshal(b, m, deterministic)
}
func (dst *ImportedDataInfo_FieldSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportedDataInfo_FieldSchema.Merge(dst, src)
}
func (m *ImportedDataInfo_FieldSchema) XXX_Size() int {
	return xxx_messageInfo_ImportedDataInfo_FieldSchema.Size(m)
}
func (m *ImportedDataInfo_FieldSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportedDataInfo_FieldSchema.DiscardUnknown(m)
}

var xxx_messageInfo_ImportedDataInfo_FieldSchema proto.InternalMessageInfo

func (m *ImportedDataInfo_FieldSchema) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *ImportedDataInfo_FieldSchema) GetType() ImportedDataInfo_FieldSchema_Type {
	if m != nil {
		return m.Type
	}
	return ImportedDataInfo_FieldSchema_TYPE_UNSPECIFIED
}

func (m *ImportedDataInfo_FieldSchema) GetIsRepeated() bool {
	if m != nil {
		return m.IsRepeated
	}
	return false
}

func (m *ImportedDataInfo_FieldSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ImportedDataInfo_FieldSchema) GetSchema() *ImportedDataInfo_RecordSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

// Describes schema of the data to be ingested.
type ImportedDataInfo_RecordSchema struct {
	// One field per column in the record.
	Fields               []*ImportedDataInfo_FieldSchema `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ImportedDataInfo_RecordSchema) Reset()         { *m = ImportedDataInfo_RecordSchema{} }
func (m *ImportedDataInfo_RecordSchema) String() string { return proto.CompactTextString(m) }
func (*ImportedDataInfo_RecordSchema) ProtoMessage()    {}
func (*ImportedDataInfo_RecordSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 1}
}
func (m *ImportedDataInfo_RecordSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportedDataInfo_RecordSchema.Unmarshal(m, b)
}
func (m *ImportedDataInfo_RecordSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportedDataInfo_RecordSchema.Marshal(b, m, deterministic)
}
func (dst *ImportedDataInfo_RecordSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportedDataInfo_RecordSchema.Merge(dst, src)
}
func (m *ImportedDataInfo_RecordSchema) XXX_Size() int {
	return xxx_messageInfo_ImportedDataInfo_RecordSchema.Size(m)
}
func (m *ImportedDataInfo_RecordSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportedDataInfo_RecordSchema.DiscardUnknown(m)
}

var xxx_messageInfo_ImportedDataInfo_RecordSchema proto.InternalMessageInfo

func (m *ImportedDataInfo_RecordSchema) GetFields() []*ImportedDataInfo_FieldSchema {
	if m != nil {
		return m.Fields
	}
	return nil
}

// External table definition. These tables can be referenced with 'name'
// in the query and can be read just like any other table.
type ImportedDataInfo_TableDefinition struct {
	// BigQuery table_id (required). This will be used to reference this
	// table in the query.
	TableId string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// URIs for the data to be imported. All URIs must be from the same storage
	// system.
	SourceUris []string `protobuf:"bytes,2,rep,name=source_uris,json=sourceUris,proto3" json:"source_uris,omitempty"`
	// Describes the format of the data in source_uri.
	Format ImportedDataInfo_Format `protobuf:"varint,3,opt,name=format,proto3,enum=google.cloud.bigquery.datatransfer.v1.ImportedDataInfo_Format" json:"format,omitempty"`
	// Specify the maximum number of bad records that can be ignored.
	// If bad records exceed this threshold the query is aborted.
	MaxBadRecords int32 `protobuf:"varint,4,opt,name=max_bad_records,json=maxBadRecords,proto3" json:"max_bad_records,omitempty"`
	// Character encoding of the input when applicable (CSV, JSON).
	// Defaults to UTF8.
	Encoding ImportedDataInfo_Encoding `protobuf:"varint,5,opt,name=encoding,proto3,enum=google.cloud.bigquery.datatransfer.v1.ImportedDataInfo_Encoding" json:"encoding,omitempty"`
	// CSV specific options.
	CsvOptions *ImportedDataInfo_TableDefinition_CsvOptions `protobuf:"bytes,6,opt,name=csv_options,json=csvOptions,proto3" json:"csv_options,omitempty"`
	// Optional schema for the data. When not specified for JSON and CSV formats
	// we will try to detect it automatically.
	Schema               *ImportedDataInfo_RecordSchema `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ImportedDataInfo_TableDefinition) Reset()         { *m = ImportedDataInfo_TableDefinition{} }
func (m *ImportedDataInfo_TableDefinition) String() string { return proto.CompactTextString(m) }
func (*ImportedDataInfo_TableDefinition) ProtoMessage()    {}
func (*ImportedDataInfo_TableDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 2}
}
func (m *ImportedDataInfo_TableDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportedDataInfo_TableDefinition.Unmarshal(m, b)
}
func (m *ImportedDataInfo_TableDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportedDataInfo_TableDefinition.Marshal(b, m, deterministic)
}
func (dst *ImportedDataInfo_TableDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportedDataInfo_TableDefinition.Merge(dst, src)
}
func (m *ImportedDataInfo_TableDefinition) XXX_Size() int {
	return xxx_messageInfo_ImportedDataInfo_TableDefinition.Size(m)
}
func (m *ImportedDataInfo_TableDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportedDataInfo_TableDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_ImportedDataInfo_TableDefinition proto.InternalMessageInfo

func (m *ImportedDataInfo_TableDefinition) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

func (m *ImportedDataInfo_TableDefinition) GetSourceUris() []string {
	if m != nil {
		return m.SourceUris
	}
	return nil
}

func (m *ImportedDataInfo_TableDefinition) GetFormat() ImportedDataInfo_Format {
	if m != nil {
		return m.Format
	}
	return ImportedDataInfo_FORMAT_UNSPECIFIED
}

func (m *ImportedDataInfo_TableDefinition) GetMaxBadRecords() int32 {
	if m != nil {
		return m.MaxBadRecords
	}
	return 0
}

func (m *ImportedDataInfo_TableDefinition) GetEncoding() ImportedDataInfo_Encoding {
	if m != nil {
		return m.Encoding
	}
	return ImportedDataInfo_ENCODING_UNSPECIFIED
}

func (m *ImportedDataInfo_TableDefinition) GetCsvOptions() *ImportedDataInfo_TableDefinition_CsvOptions {
	if m != nil {
		return m.CsvOptions
	}
	return nil
}

func (m *ImportedDataInfo_TableDefinition) GetSchema() *ImportedDataInfo_RecordSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

// CSV specific options.
type ImportedDataInfo_TableDefinition_CsvOptions struct {
	// The delimiter.  We currently restrict this to U+0001 to U+00FF and
	// apply additional constraints during validation.
	FieldDelimiter *wrappers.StringValue `protobuf:"bytes,1,opt,name=field_delimiter,json=fieldDelimiter,proto3" json:"field_delimiter,omitempty"`
	// Whether CSV files are allowed to have quoted newlines. If quoted
	// newlines are allowed, we can't split CSV files.
	AllowQuotedNewlines *wrappers.BoolValue `protobuf:"bytes,2,opt,name=allow_quoted_newlines,json=allowQuotedNewlines,proto3" json:"allow_quoted_newlines,omitempty"`
	// The quote character.  We currently restrict this to U+0000 to U+00FF
	// and apply additional constraints during validation. Set to '\0' to
	// indicate no quote is used.
	QuoteChar *wrappers.StringValue `protobuf:"bytes,3,opt,name=quote_char,json=quoteChar,proto3" json:"quote_char,omitempty"`
	// Number of leading rows to skip.
	SkipLeadingRows      *wrappers.Int64Value `protobuf:"bytes,4,opt,name=skip_leading_rows,json=skipLeadingRows,proto3" json:"skip_leading_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ImportedDataInfo_TableDefinition_CsvOptions) Reset() {
	*m = ImportedDataInfo_TableDefinition_CsvOptions{}
}
func (m *ImportedDataInfo_TableDefinition_CsvOptions) String() string {
	return proto.CompactTextString(m)
}
func (*ImportedDataInfo_TableDefinition_CsvOptions) ProtoMessage() {}
func (*ImportedDataInfo_TableDefinition_CsvOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{0, 2, 0}
}
func (m *ImportedDataInfo_TableDefinition_CsvOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportedDataInfo_TableDefinition_CsvOptions.Unmarshal(m, b)
}
func (m *ImportedDataInfo_TableDefinition_CsvOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportedDataInfo_TableDefinition_CsvOptions.Marshal(b, m, deterministic)
}
func (dst *ImportedDataInfo_TableDefinition_CsvOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportedDataInfo_TableDefinition_CsvOptions.Merge(dst, src)
}
func (m *ImportedDataInfo_TableDefinition_CsvOptions) XXX_Size() int {
	return xxx_messageInfo_ImportedDataInfo_TableDefinition_CsvOptions.Size(m)
}
func (m *ImportedDataInfo_TableDefinition_CsvOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportedDataInfo_TableDefinition_CsvOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ImportedDataInfo_TableDefinition_CsvOptions proto.InternalMessageInfo

func (m *ImportedDataInfo_TableDefinition_CsvOptions) GetFieldDelimiter() *wrappers.StringValue {
	if m != nil {
		return m.FieldDelimiter
	}
	return nil
}

func (m *ImportedDataInfo_TableDefinition_CsvOptions) GetAllowQuotedNewlines() *wrappers.BoolValue {
	if m != nil {
		return m.AllowQuotedNewlines
	}
	return nil
}

func (m *ImportedDataInfo_TableDefinition_CsvOptions) GetQuoteChar() *wrappers.StringValue {
	if m != nil {
		return m.QuoteChar
	}
	return nil
}

func (m *ImportedDataInfo_TableDefinition_CsvOptions) GetSkipLeadingRows() *wrappers.Int64Value {
	if m != nil {
		return m.SkipLeadingRows
	}
	return nil
}

// A request to update a transfer run.
type UpdateTransferRunRequest struct {
	// Run name must be set and correspond to an already existing run. Only
	// state, error_status, and data_version fields will be updated. All other
	// fields will be ignored.
	TransferRun *TransferRun `protobuf:"bytes,1,opt,name=transfer_run,json=transferRun,proto3" json:"transfer_run,omitempty"`
	// Required list of fields to be updated in this request.
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateTransferRunRequest) Reset()         { *m = UpdateTransferRunRequest{} }
func (m *UpdateTransferRunRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTransferRunRequest) ProtoMessage()    {}
func (*UpdateTransferRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{1}
}
func (m *UpdateTransferRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTransferRunRequest.Unmarshal(m, b)
}
func (m *UpdateTransferRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTransferRunRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTransferRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTransferRunRequest.Merge(dst, src)
}
func (m *UpdateTransferRunRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTransferRunRequest.Size(m)
}
func (m *UpdateTransferRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTransferRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTransferRunRequest proto.InternalMessageInfo

func (m *UpdateTransferRunRequest) GetTransferRun() *TransferRun {
	if m != nil {
		return m.TransferRun
	}
	return nil
}

func (m *UpdateTransferRunRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// A request to add transfer status messages to the run.
type LogTransferRunMessagesRequest struct {
	// Name of the resource in the form:
	// "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Messages to append.
	TransferMessages     []*TransferMessage `protobuf:"bytes,2,rep,name=transfer_messages,json=transferMessages,proto3" json:"transfer_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LogTransferRunMessagesRequest) Reset()         { *m = LogTransferRunMessagesRequest{} }
func (m *LogTransferRunMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*LogTransferRunMessagesRequest) ProtoMessage()    {}
func (*LogTransferRunMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{2}
}
func (m *LogTransferRunMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogTransferRunMessagesRequest.Unmarshal(m, b)
}
func (m *LogTransferRunMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogTransferRunMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *LogTransferRunMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogTransferRunMessagesRequest.Merge(dst, src)
}
func (m *LogTransferRunMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_LogTransferRunMessagesRequest.Size(m)
}
func (m *LogTransferRunMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogTransferRunMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogTransferRunMessagesRequest proto.InternalMessageInfo

func (m *LogTransferRunMessagesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogTransferRunMessagesRequest) GetTransferMessages() []*TransferMessage {
	if m != nil {
		return m.TransferMessages
	}
	return nil
}

// A request to start and monitor a BigQuery load job.
type StartBigQueryJobsRequest struct {
	// Name of the resource in the form:
	// "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Import jobs which should be started and monitored.
	ImportedData []*ImportedDataInfo `protobuf:"bytes,2,rep,name=imported_data,json=importedData,proto3" json:"imported_data,omitempty"`
	// User credentials which should be used to start/monitor
	// BigQuery jobs. If not specified, then jobs
	// are started using data source service account credentials.
	// This may be OAuth token or JWT token.
	UserCredentials      []byte   `protobuf:"bytes,3,opt,name=user_credentials,json=userCredentials,proto3" json:"user_credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBigQueryJobsRequest) Reset()         { *m = StartBigQueryJobsRequest{} }
func (m *StartBigQueryJobsRequest) String() string { return proto.CompactTextString(m) }
func (*StartBigQueryJobsRequest) ProtoMessage()    {}
func (*StartBigQueryJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{3}
}
func (m *StartBigQueryJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBigQueryJobsRequest.Unmarshal(m, b)
}
func (m *StartBigQueryJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBigQueryJobsRequest.Marshal(b, m, deterministic)
}
func (dst *StartBigQueryJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBigQueryJobsRequest.Merge(dst, src)
}
func (m *StartBigQueryJobsRequest) XXX_Size() int {
	return xxx_messageInfo_StartBigQueryJobsRequest.Size(m)
}
func (m *StartBigQueryJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBigQueryJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartBigQueryJobsRequest proto.InternalMessageInfo

func (m *StartBigQueryJobsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StartBigQueryJobsRequest) GetImportedData() []*ImportedDataInfo {
	if m != nil {
		return m.ImportedData
	}
	return nil
}

func (m *StartBigQueryJobsRequest) GetUserCredentials() []byte {
	if m != nil {
		return m.UserCredentials
	}
	return nil
}

// A request to finish a run.
type FinishRunRequest struct {
	// Name of the resource in the form:
	// "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishRunRequest) Reset()         { *m = FinishRunRequest{} }
func (m *FinishRunRequest) String() string { return proto.CompactTextString(m) }
func (*FinishRunRequest) ProtoMessage()    {}
func (*FinishRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{4}
}
func (m *FinishRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishRunRequest.Unmarshal(m, b)
}
func (m *FinishRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishRunRequest.Marshal(b, m, deterministic)
}
func (dst *FinishRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishRunRequest.Merge(dst, src)
}
func (m *FinishRunRequest) XXX_Size() int {
	return xxx_messageInfo_FinishRunRequest.Size(m)
}
func (m *FinishRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishRunRequest proto.InternalMessageInfo

func (m *FinishRunRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Represents GetCredentials rpc request.
type GetCredentialsRequest struct {
	// Name of this credentials object in the form
	// projects/-/locations/{location_id}/dataSources/{data_source_id}/credentials/{user_id}
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCredentialsRequest) Reset()         { *m = GetCredentialsRequest{} }
func (m *GetCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCredentialsRequest) ProtoMessage()    {}
func (*GetCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{5}
}
func (m *GetCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCredentialsRequest.Unmarshal(m, b)
}
func (m *GetCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCredentialsRequest.Marshal(b, m, deterministic)
}
func (dst *GetCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCredentialsRequest.Merge(dst, src)
}
func (m *GetCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCredentialsRequest.Size(m)
}
func (m *GetCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCredentialsRequest proto.InternalMessageInfo

func (m *GetCredentialsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Credentials for User associated with a specific data source.
type Credentials struct {
	// Name of this credentials object in the form
	// projects/-/locations/{location_id}/dataSources/{data_source_id}/credentials/{user_id}
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Auth token which can be used to perform requests on behalf of the user.
	AuthToken            string   `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{6}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Credentials) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

// Represents the request of the CreateDataSourceDefinition method.
type CreateDataSourceDefinitionRequest struct {
	// The BigQuery project id for which data source definition is associated.
	// Must be in the form: `projects/{project_id}/locations/{location_id}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Data source definition.
	DataSourceDefinition *DataSourceDefinition `protobuf:"bytes,2,opt,name=data_source_definition,json=dataSourceDefinition,proto3" json:"data_source_definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateDataSourceDefinitionRequest) Reset()         { *m = CreateDataSourceDefinitionRequest{} }
func (m *CreateDataSourceDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDataSourceDefinitionRequest) ProtoMessage()    {}
func (*CreateDataSourceDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{7}
}
func (m *CreateDataSourceDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDataSourceDefinitionRequest.Unmarshal(m, b)
}
func (m *CreateDataSourceDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDataSourceDefinitionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDataSourceDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDataSourceDefinitionRequest.Merge(dst, src)
}
func (m *CreateDataSourceDefinitionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDataSourceDefinitionRequest.Size(m)
}
func (m *CreateDataSourceDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDataSourceDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDataSourceDefinitionRequest proto.InternalMessageInfo

func (m *CreateDataSourceDefinitionRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateDataSourceDefinitionRequest) GetDataSourceDefinition() *DataSourceDefinition {
	if m != nil {
		return m.DataSourceDefinition
	}
	return nil
}

// Represents the request of the UpdateDataSourceDefinition method.
type UpdateDataSourceDefinitionRequest struct {
	// Data source definition.
	DataSourceDefinition *DataSourceDefinition `protobuf:"bytes,1,opt,name=data_source_definition,json=dataSourceDefinition,proto3" json:"data_source_definition,omitempty"`
	// Update field mask.
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateDataSourceDefinitionRequest) Reset()         { *m = UpdateDataSourceDefinitionRequest{} }
func (m *UpdateDataSourceDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDataSourceDefinitionRequest) ProtoMessage()    {}
func (*UpdateDataSourceDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{8}
}
func (m *UpdateDataSourceDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDataSourceDefinitionRequest.Unmarshal(m, b)
}
func (m *UpdateDataSourceDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDataSourceDefinitionRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDataSourceDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDataSourceDefinitionRequest.Merge(dst, src)
}
func (m *UpdateDataSourceDefinitionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDataSourceDefinitionRequest.Size(m)
}
func (m *UpdateDataSourceDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDataSourceDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDataSourceDefinitionRequest proto.InternalMessageInfo

func (m *UpdateDataSourceDefinitionRequest) GetDataSourceDefinition() *DataSourceDefinition {
	if m != nil {
		return m.DataSourceDefinition
	}
	return nil
}

func (m *UpdateDataSourceDefinitionRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// Represents the request of the DeleteDataSourceDefinition method. All transfer
// configs associated with the data source must be deleted first, before the
// data source can be deleted.
type DeleteDataSourceDefinitionRequest struct {
	// The field will contain name of the resource requested, for example:
	// `projects/{project_id}/locations/{location_id}/dataSourceDefinitions/{data_source_id}`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataSourceDefinitionRequest) Reset()         { *m = DeleteDataSourceDefinitionRequest{} }
func (m *DeleteDataSourceDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDataSourceDefinitionRequest) ProtoMessage()    {}
func (*DeleteDataSourceDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{9}
}
func (m *DeleteDataSourceDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataSourceDefinitionRequest.Unmarshal(m, b)
}
func (m *DeleteDataSourceDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataSourceDefinitionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDataSourceDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataSourceDefinitionRequest.Merge(dst, src)
}
func (m *DeleteDataSourceDefinitionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDataSourceDefinitionRequest.Size(m)
}
func (m *DeleteDataSourceDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataSourceDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataSourceDefinitionRequest proto.InternalMessageInfo

func (m *DeleteDataSourceDefinitionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Represents the request of the GetDataSourceDefinition method.
type GetDataSourceDefinitionRequest struct {
	// The field will contain name of the resource requested.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataSourceDefinitionRequest) Reset()         { *m = GetDataSourceDefinitionRequest{} }
func (m *GetDataSourceDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataSourceDefinitionRequest) ProtoMessage()    {}
func (*GetDataSourceDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{10}
}
func (m *GetDataSourceDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataSourceDefinitionRequest.Unmarshal(m, b)
}
func (m *GetDataSourceDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataSourceDefinitionRequest.Marshal(b, m, deterministic)
}
func (dst *GetDataSourceDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataSourceDefinitionRequest.Merge(dst, src)
}
func (m *GetDataSourceDefinitionRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataSourceDefinitionRequest.Size(m)
}
func (m *GetDataSourceDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataSourceDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataSourceDefinitionRequest proto.InternalMessageInfo

func (m *GetDataSourceDefinitionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Represents the request of the ListDataSourceDefinitions method.
type ListDataSourceDefinitionsRequest struct {
	// The BigQuery project id for which data sources should be returned.
	// Must be in the form: `projects/{project_id}/locations/{location_id}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Pagination token, which can be used to request a specific page
	// of `ListDataSourceDefinitionsRequest` list results. For multiple-page
	// results, `ListDataSourceDefinitionsResponse` outputs a `next_page` token,
	// which can be used as the `page_token` value to request the next page of
	// the list results.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Page size. The default page size is the maximum value of 1000 results.
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDataSourceDefinitionsRequest) Reset()         { *m = ListDataSourceDefinitionsRequest{} }
func (m *ListDataSourceDefinitionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDataSourceDefinitionsRequest) ProtoMessage()    {}
func (*ListDataSourceDefinitionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{11}
}
func (m *ListDataSourceDefinitionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDataSourceDefinitionsRequest.Unmarshal(m, b)
}
func (m *ListDataSourceDefinitionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDataSourceDefinitionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListDataSourceDefinitionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDataSourceDefinitionsRequest.Merge(dst, src)
}
func (m *ListDataSourceDefinitionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDataSourceDefinitionsRequest.Size(m)
}
func (m *ListDataSourceDefinitionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDataSourceDefinitionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDataSourceDefinitionsRequest proto.InternalMessageInfo

func (m *ListDataSourceDefinitionsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListDataSourceDefinitionsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListDataSourceDefinitionsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// Returns a list of supported data source definitions.
type ListDataSourceDefinitionsResponse struct {
	// List of supported data source definitions.
	DataSourceDefinitions []*DataSourceDefinition `protobuf:"bytes,1,rep,name=data_source_definitions,json=dataSourceDefinitions,proto3" json:"data_source_definitions,omitempty"`
	// Output only. The next-pagination token. For multiple-page list results,
	// this token can be used as the
	// `ListDataSourceDefinitionsRequest.page_token`
	// to request the next page of the list results.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDataSourceDefinitionsResponse) Reset()         { *m = ListDataSourceDefinitionsResponse{} }
func (m *ListDataSourceDefinitionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDataSourceDefinitionsResponse) ProtoMessage()    {}
func (*ListDataSourceDefinitionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{12}
}
func (m *ListDataSourceDefinitionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDataSourceDefinitionsResponse.Unmarshal(m, b)
}
func (m *ListDataSourceDefinitionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDataSourceDefinitionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListDataSourceDefinitionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDataSourceDefinitionsResponse.Merge(dst, src)
}
func (m *ListDataSourceDefinitionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDataSourceDefinitionsResponse.Size(m)
}
func (m *ListDataSourceDefinitionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDataSourceDefinitionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDataSourceDefinitionsResponse proto.InternalMessageInfo

func (m *ListDataSourceDefinitionsResponse) GetDataSourceDefinitions() []*DataSourceDefinition {
	if m != nil {
		return m.DataSourceDefinitions
	}
	return nil
}

func (m *ListDataSourceDefinitionsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Represents the data source definition.
type DataSourceDefinition struct {
	// The resource name of the data source definition.
	// Data source definition names have the form
	// `projects/{project_id}/locations/{location}/dataSourceDefinitions/{data_source_id}`.
	Name string `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`
	// Data source metadata.
	DataSource *DataSource `protobuf:"bytes,1,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	// Output only. The pubsub topic to be used for broadcasting a message when a
	// transfer run is created. The comments about "{region}" for
	// transfer_config_pubsub_topic apply here too.
	TransferRunPubsubTopic string `protobuf:"bytes,13,opt,name=transfer_run_pubsub_topic,json=transferRunPubsubTopic,proto3" json:"transfer_run_pubsub_topic,omitempty"`
	// Duration which should be added to schedule_time to calculate
	// run_time when job is scheduled. Only applicable for automatically
	// scheduled transfer runs. Used to start a run early on a data source that
	// supports continuous data refresh to compensate for unknown timezone
	// offsets. Use a negative number to start a run late for data sources not
	// supporting continuous data refresh.
	RunTimeOffset *duration.Duration `protobuf:"bytes,16,opt,name=run_time_offset,json=runTimeOffset,proto3" json:"run_time_offset,omitempty"`
	// Support e-mail address of the OAuth client's Brand, which contains the
	// consent screen data.
	SupportEmail string `protobuf:"bytes,22,opt,name=support_email,json=supportEmail,proto3" json:"support_email,omitempty"`
	// Is data source disabled? If true, data_source is not visible.
	// API will also stop returning any data transfer configs and/or runs
	// associated with the data source. This setting has higher priority
	// than whitelisted_project_ids.
	Disabled bool `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Supported location_ids of the data source. The valid values are the
	// "location_id" field of the response of
	// `GET
	// https://bigquerydatatransfer.googleapis.com/v1/{name=projects/*}/locations`
	// In addition, if the data source needs to support all available regions,
	// supported_location_ids can be set to "global" (a single string element).
	// When "global" is specified:
	// 1) the data source implementation is supposed to stage the data in proper
	// region of the destination dataset;
	// 2) Data source developer should be aware of the implications (e.g., network
	// traffic latency, potential charge associated with cross-region traffic,
	// etc.) of supporting the "global" region;
	// 3) when new regions are added in Data Transfer Service, the new
	// regions will be treated as "supported" automatically (that is, no need to
	// update the supported_location_ids field).
	SupportedLocationIds []string `protobuf:"bytes,23,rep,name=supported_location_ids,json=supportedLocationIds,proto3" json:"supported_location_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataSourceDefinition) Reset()         { *m = DataSourceDefinition{} }
func (m *DataSourceDefinition) String() string { return proto.CompactTextString(m) }
func (*DataSourceDefinition) ProtoMessage()    {}
func (*DataSourceDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_datasource_244fd0e6c9f03398, []int{13}
}
func (m *DataSourceDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSourceDefinition.Unmarshal(m, b)
}
func (m *DataSourceDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSourceDefinition.Marshal(b, m, deterministic)
}
func (dst *DataSourceDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSourceDefinition.Merge(dst, src)
}
func (m *DataSourceDefinition) XXX_Size() int {
	return xxx_messageInfo_DataSourceDefinition.Size(m)
}
func (m *DataSourceDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSourceDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_DataSourceDefinition proto.InternalMessageInfo

func (m *DataSourceDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataSourceDefinition) GetDataSource() *DataSource {
	if m != nil {
		return m.DataSource
	}
	return nil
}

func (m *DataSourceDefinition) GetTransferRunPubsubTopic() string {
	if m != nil {
		return m.TransferRunPubsubTopic
	}
	return ""
}

func (m *DataSourceDefinition) GetRunTimeOffset() *duration.Duration {
	if m != nil {
		return m.RunTimeOffset
	}
	return nil
}

func (m *DataSourceDefinition) GetSupportEmail() string {
	if m != nil {
		return m.SupportEmail
	}
	return ""
}

func (m *DataSourceDefinition) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *DataSourceDefinition) GetSupportedLocationIds() []string {
	if m != nil {
		return m.SupportedLocationIds
	}
	return nil
}

func init() {
	proto.RegisterType((*ImportedDataInfo)(nil), "google.cloud.bigquery.datatransfer.v1.ImportedDataInfo")
	proto.RegisterType((*ImportedDataInfo_FieldSchema)(nil), "google.cloud.bigquery.datatransfer.v1.ImportedDataInfo.FieldSchema")
	proto.RegisterType((*ImportedDataInfo_RecordSchema)(nil), "google.cloud.bigquery.datatransfer.v1.ImportedDataInfo.RecordSchema")
	proto.RegisterType((*ImportedDataInfo_TableDefinition)(nil), "google.cloud.bigquery.datatransfer.v1.ImportedDataInfo.TableDefinition")
	proto.RegisterType((*ImportedDataInfo_TableDefinition_CsvOptions)(nil), "google.cloud.bigquery.datatransfer.v1.ImportedDataInfo.TableDefinition.CsvOptions")
	proto.RegisterType((*UpdateTransferRunRequest)(nil), "google.cloud.bigquery.datatransfer.v1.UpdateTransferRunRequest")
	proto.RegisterType((*LogTransferRunMessagesRequest)(nil), "google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest")
	proto.RegisterType((*StartBigQueryJobsRequest)(nil), "google.cloud.bigquery.datatransfer.v1.StartBigQueryJobsRequest")
	proto.RegisterType((*FinishRunRequest)(nil), "google.cloud.bigquery.datatransfer.v1.FinishRunRequest")
	proto.RegisterType((*GetCredentialsRequest)(nil), "google.cloud.bigquery.datatransfer.v1.GetCredentialsRequest")
	proto.RegisterType((*Credentials)(nil), "google.cloud.bigquery.datatransfer.v1.Credentials")
	proto.RegisterType((*CreateDataSourceDefinitionRequest)(nil), "google.cloud.bigquery.datatransfer.v1.CreateDataSourceDefinitionRequest")
	proto.RegisterType((*UpdateDataSourceDefinitionRequest)(nil), "google.cloud.bigquery.datatransfer.v1.UpdateDataSourceDefinitionRequest")
	proto.RegisterType((*DeleteDataSourceDefinitionRequest)(nil), "google.cloud.bigquery.datatransfer.v1.DeleteDataSourceDefinitionRequest")
	proto.RegisterType((*GetDataSourceDefinitionRequest)(nil), "google.cloud.bigquery.datatransfer.v1.GetDataSourceDefinitionRequest")
	proto.RegisterType((*ListDataSourceDefinitionsRequest)(nil), "google.cloud.bigquery.datatransfer.v1.ListDataSourceDefinitionsRequest")
	proto.RegisterType((*ListDataSourceDefinitionsResponse)(nil), "google.cloud.bigquery.datatransfer.v1.ListDataSourceDefinitionsResponse")
	proto.RegisterType((*DataSourceDefinition)(nil), "google.cloud.bigquery.datatransfer.v1.DataSourceDefinition")
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.ImportedDataInfo_Format", ImportedDataInfo_Format_name, ImportedDataInfo_Format_value)
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.ImportedDataInfo_Encoding", ImportedDataInfo_Encoding_name, ImportedDataInfo_Encoding_value)
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.ImportedDataInfo_FieldSchema_Type", ImportedDataInfo_FieldSchema_Type_name, ImportedDataInfo_FieldSchema_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataSourceServiceClient is the client API for DataSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataSourceServiceClient interface {
	// Update a transfer run. If successful, resets
	// data_source.update_deadline_seconds timer.
	UpdateTransferRun(ctx context.Context, in *UpdateTransferRunRequest, opts ...grpc.CallOption) (*TransferRun, error)
	// Log messages for a transfer run. If successful (at least 1 message), resets
	// data_source.update_deadline_seconds timer.
	LogTransferRunMessages(ctx context.Context, in *LogTransferRunMessagesRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Notify the Data Transfer Service that data is ready for loading.
	// The Data Transfer Service will start and monitor multiple BigQuery Load
	// jobs for a transfer run. Monitored jobs will be automatically retried
	// and produce log messages when starting and finishing a job.
	// Can be called multiple times for the same transfer run.
	StartBigQueryJobs(ctx context.Context, in *StartBigQueryJobsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get user authentication token so that the data source can perform
	// operations on behalf of the user.
	// Can only be called by configured data source service account.
	// In all other cases - it will fail with permission denied error.
	GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*Credentials, error)
	// Notify the Data Transfer Service that the data source is done processing
	// the run. No more status updates or requests to start/monitor jobs will be
	// accepted. The run will be finalized by the Data Transfer Service when all
	// monitored jobs are completed.
	// Does not need to be called if the run is set to FAILED.
	FinishRun(ctx context.Context, in *FinishRunRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Creates a data source definition.  Calling this method will automatically
	// use your credentials to create the following Google Cloud resources in
	// YOUR Google Cloud project.
	// 1. OAuth client
	// 2. Pub/Sub Topics and Subscriptions in each supported_location_ids. e.g.,
	// projects/{project_id}/{topics|subscriptions}/bigquerydatatransfer.{data_source_id}.{location_id}.run
	// The field data_source.client_id should be left empty in the input request,
	// as the API will create a new OAuth client on behalf of the caller. On the
	// other hand data_source.scopes usually need to be set when there are OAuth
	// scopes that need to be granted by end users.
	CreateDataSourceDefinition(ctx context.Context, in *CreateDataSourceDefinitionRequest, opts ...grpc.CallOption) (*DataSourceDefinition, error)
	// Updates an existing data source definition. If changing
	// supported_location_ids, triggers same effects as mentioned in "Create a
	// data source definition."
	UpdateDataSourceDefinition(ctx context.Context, in *UpdateDataSourceDefinitionRequest, opts ...grpc.CallOption) (*DataSourceDefinition, error)
	// Deletes a data source definition, all of the transfer configs associated
	// with this data source definition (if any) must be deleted first by the user
	// in ALL regions, in order to delete the data source definition.
	// This method is primarily meant for deleting data sources created during
	// testing stage.
	// If the data source is referenced by transfer configs in the region
	// specified in the request URL, the method will fail immediately. If in the
	// current region (e.g., US) it's not used by any transfer configs, but in
	// another region (e.g., EU) it is, then although the method will succeed in
	// region US, but it will fail when the deletion operation is replicated to
	// region EU. And eventually, the system will replicate the data source
	// definition back from EU to US, in order to bring all regions to
	// consistency. The final effect is that the data source appears to be
	// 'undeleted' in the US region.
	DeleteDataSourceDefinition(ctx context.Context, in *DeleteDataSourceDefinitionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves an existing data source definition.
	GetDataSourceDefinition(ctx context.Context, in *GetDataSourceDefinitionRequest, opts ...grpc.CallOption) (*DataSourceDefinition, error)
	// Lists supported data source definitions.
	ListDataSourceDefinitions(ctx context.Context, in *ListDataSourceDefinitionsRequest, opts ...grpc.CallOption) (*ListDataSourceDefinitionsResponse, error)
}

type dataSourceServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataSourceServiceClient(cc *grpc.ClientConn) DataSourceServiceClient {
	return &dataSourceServiceClient{cc}
}

func (c *dataSourceServiceClient) UpdateTransferRun(ctx context.Context, in *UpdateTransferRunRequest, opts ...grpc.CallOption) (*TransferRun, error) {
	out := new(TransferRun)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/UpdateTransferRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) LogTransferRunMessages(ctx context.Context, in *LogTransferRunMessagesRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/LogTransferRunMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) StartBigQueryJobs(ctx context.Context, in *StartBigQueryJobsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/StartBigQueryJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*Credentials, error) {
	out := new(Credentials)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/GetCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) FinishRun(ctx context.Context, in *FinishRunRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/FinishRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) CreateDataSourceDefinition(ctx context.Context, in *CreateDataSourceDefinitionRequest, opts ...grpc.CallOption) (*DataSourceDefinition, error) {
	out := new(DataSourceDefinition)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/CreateDataSourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) UpdateDataSourceDefinition(ctx context.Context, in *UpdateDataSourceDefinitionRequest, opts ...grpc.CallOption) (*DataSourceDefinition, error) {
	out := new(DataSourceDefinition)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/UpdateDataSourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) DeleteDataSourceDefinition(ctx context.Context, in *DeleteDataSourceDefinitionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/DeleteDataSourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) GetDataSourceDefinition(ctx context.Context, in *GetDataSourceDefinitionRequest, opts ...grpc.CallOption) (*DataSourceDefinition, error) {
	out := new(DataSourceDefinition)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/GetDataSourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) ListDataSourceDefinitions(ctx context.Context, in *ListDataSourceDefinitionsRequest, opts ...grpc.CallOption) (*ListDataSourceDefinitionsResponse, error) {
	out := new(ListDataSourceDefinitionsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.bigquery.datatransfer.v1.DataSourceService/ListDataSourceDefinitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourceServiceServer is the server API for DataSourceService service.
type DataSourceServiceServer interface {
	// Update a transfer run. If successful, resets
	// data_source.update_deadline_seconds timer.
	UpdateTransferRun(context.Context, *UpdateTransferRunRequest) (*TransferRun, error)
	// Log messages for a transfer run. If successful (at least 1 message), resets
	// data_source.update_deadline_seconds timer.
	LogTransferRunMessages(context.Context, *LogTransferRunMessagesRequest) (*empty.Empty, error)
	// Notify the Data Transfer Service that data is ready for loading.
	// The Data Transfer Service will start and monitor multiple BigQuery Load
	// jobs for a transfer run. Monitored jobs will be automatically retried
	// and produce log messages when starting and finishing a job.
	// Can be called multiple times for the same transfer run.
	StartBigQueryJobs(context.Context, *StartBigQueryJobsRequest) (*empty.Empty, error)
	// Get user authentication token so that the data source can perform
	// operations on behalf of the user.
	// Can only be called by configured data source service account.
	// In all other cases - it will fail with permission denied error.
	GetCredentials(context.Context, *GetCredentialsRequest) (*Credentials, error)
	// Notify the Data Transfer Service that the data source is done processing
	// the run. No more status updates or requests to start/monitor jobs will be
	// accepted. The run will be finalized by the Data Transfer Service when all
	// monitored jobs are completed.
	// Does not need to be called if the run is set to FAILED.
	FinishRun(context.Context, *FinishRunRequest) (*empty.Empty, error)
	// Creates a data source definition.  Calling this method will automatically
	// use your credentials to create the following Google Cloud resources in
	// YOUR Google Cloud project.
	// 1. OAuth client
	// 2. Pub/Sub Topics and Subscriptions in each supported_location_ids. e.g.,
	// projects/{project_id}/{topics|subscriptions}/bigquerydatatransfer.{data_source_id}.{location_id}.run
	// The field data_source.client_id should be left empty in the input request,
	// as the API will create a new OAuth client on behalf of the caller. On the
	// other hand data_source.scopes usually need to be set when there are OAuth
	// scopes that need to be granted by end users.
	CreateDataSourceDefinition(context.Context, *CreateDataSourceDefinitionRequest) (*DataSourceDefinition, error)
	// Updates an existing data source definition. If changing
	// supported_location_ids, triggers same effects as mentioned in "Create a
	// data source definition."
	UpdateDataSourceDefinition(context.Context, *UpdateDataSourceDefinitionRequest) (*DataSourceDefinition, error)
	// Deletes a data source definition, all of the transfer configs associated
	// with this data source definition (if any) must be deleted first by the user
	// in ALL regions, in order to delete the data source definition.
	// This method is primarily meant for deleting data sources created during
	// testing stage.
	// If the data source is referenced by transfer configs in the region
	// specified in the request URL, the method will fail immediately. If in the
	// current region (e.g., US) it's not used by any transfer configs, but in
	// another region (e.g., EU) it is, then although the method will succeed in
	// region US, but it will fail when the deletion operation is replicated to
	// region EU. And eventually, the system will replicate the data source
	// definition back from EU to US, in order to bring all regions to
	// consistency. The final effect is that the data source appears to be
	// 'undeleted' in the US region.
	DeleteDataSourceDefinition(context.Context, *DeleteDataSourceDefinitionRequest) (*empty.Empty, error)
	// Retrieves an existing data source definition.
	GetDataSourceDefinition(context.Context, *GetDataSourceDefinitionRequest) (*DataSourceDefinition, error)
	// Lists supported data source definitions.
	ListDataSourceDefinitions(context.Context, *ListDataSourceDefinitionsRequest) (*ListDataSourceDefinitionsResponse, error)
}

func RegisterDataSourceServiceServer(s *grpc.Server, srv DataSourceServiceServer) {
	s.RegisterService(&_DataSourceService_serviceDesc, srv)
}

func _DataSourceService_UpdateTransferRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransferRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).UpdateTransferRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/UpdateTransferRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).UpdateTransferRun(ctx, req.(*UpdateTransferRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_LogTransferRunMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogTransferRunMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).LogTransferRunMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/LogTransferRunMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).LogTransferRunMessages(ctx, req.(*LogTransferRunMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_StartBigQueryJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBigQueryJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).StartBigQueryJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/StartBigQueryJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).StartBigQueryJobs(ctx, req.(*StartBigQueryJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/GetCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).GetCredentials(ctx, req.(*GetCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_FinishRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).FinishRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/FinishRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).FinishRun(ctx, req.(*FinishRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_CreateDataSourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataSourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).CreateDataSourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/CreateDataSourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).CreateDataSourceDefinition(ctx, req.(*CreateDataSourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_UpdateDataSourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).UpdateDataSourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/UpdateDataSourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).UpdateDataSourceDefinition(ctx, req.(*UpdateDataSourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_DeleteDataSourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataSourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).DeleteDataSourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/DeleteDataSourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).DeleteDataSourceDefinition(ctx, req.(*DeleteDataSourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_GetDataSourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).GetDataSourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/GetDataSourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).GetDataSourceDefinition(ctx, req.(*GetDataSourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_ListDataSourceDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourceDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).ListDataSourceDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.bigquery.datatransfer.v1.DataSourceService/ListDataSourceDefinitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).ListDataSourceDefinitions(ctx, req.(*ListDataSourceDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataSourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.bigquery.datatransfer.v1.DataSourceService",
	HandlerType: (*DataSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTransferRun",
			Handler:    _DataSourceService_UpdateTransferRun_Handler,
		},
		{
			MethodName: "LogTransferRunMessages",
			Handler:    _DataSourceService_LogTransferRunMessages_Handler,
		},
		{
			MethodName: "StartBigQueryJobs",
			Handler:    _DataSourceService_StartBigQueryJobs_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _DataSourceService_GetCredentials_Handler,
		},
		{
			MethodName: "FinishRun",
			Handler:    _DataSourceService_FinishRun_Handler,
		},
		{
			MethodName: "CreateDataSourceDefinition",
			Handler:    _DataSourceService_CreateDataSourceDefinition_Handler,
		},
		{
			MethodName: "UpdateDataSourceDefinition",
			Handler:    _DataSourceService_UpdateDataSourceDefinition_Handler,
		},
		{
			MethodName: "DeleteDataSourceDefinition",
			Handler:    _DataSourceService_DeleteDataSourceDefinition_Handler,
		},
		{
			MethodName: "GetDataSourceDefinition",
			Handler:    _DataSourceService_GetDataSourceDefinition_Handler,
		},
		{
			MethodName: "ListDataSourceDefinitions",
			Handler:    _DataSourceService_ListDataSourceDefinitions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/bigquery/datatransfer/v1/datasource.proto",
}

func init() {
	proto.RegisterFile("google/cloud/bigquery/datatransfer/v1/datasource.proto", fileDescriptor_datasource_244fd0e6c9f03398)
}

var fileDescriptor_datasource_244fd0e6c9f03398 = []byte{
	// 2067 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0x4d, 0x4f, 0x23, 0xc9,
	0xf9, 0xff, 0xb7, 0x0d, 0xc6, 0x7e, 0xcc, 0x4b, 0x53, 0x7f, 0x86, 0xf1, 0x78, 0x76, 0x76, 0x18,
	0x47, 0xbb, 0x62, 0x26, 0x92, 0xbd, 0x38, 0x93, 0xd9, 0x61, 0xc8, 0xbe, 0x18, 0xdb, 0x30, 0xde,
	0x80, 0x6d, 0xda, 0x86, 0xd5, 0x24, 0x44, 0xad, 0xc2, 0x5d, 0x36, 0xbd, 0xd8, 0xdd, 0x4d, 0x57,
	0x35, 0x0c, 0x1b, 0x4d, 0x0e, 0xf9, 0x0a, 0x51, 0xa4, 0x9c, 0x73, 0xcb, 0x4a, 0xc9, 0x35, 0xd7,
	0xec, 0x21, 0x87, 0xcd, 0x29, 0xd2, 0x7e, 0x81, 0x44, 0x4a, 0x94, 0x73, 0x94, 0x7b, 0x14, 0x55,
	0x75, 0xb5, 0xe9, 0x31, 0x36, 0x78, 0x60, 0xf6, 0xd6, 0xf5, 0xbc, 0xbf, 0xfc, 0xaa, 0x9e, 0xc7,
	0x00, 0x4f, 0x3a, 0xb6, 0xdd, 0xe9, 0x92, 0x5c, 0xab, 0x6b, 0x7b, 0x46, 0xee, 0xc0, 0xec, 0x1c,
	0x7b, 0xc4, 0x3d, 0xcb, 0x19, 0x98, 0x61, 0xe6, 0x62, 0x8b, 0xb6, 0x89, 0x9b, 0x3b, 0x59, 0x11,
	0x67, 0x6a, 0x7b, 0x6e, 0x8b, 0x64, 0x1d, 0xd7, 0x66, 0x36, 0x7a, 0xcf, 0xd7, 0xcb, 0x0a, 0xbd,
	0x6c, 0xa0, 0x97, 0x0d, 0xeb, 0x65, 0x4f, 0x56, 0xd2, 0xef, 0x48, 0xf3, 0xd8, 0x31, 0x73, 0xd8,
	0xb2, 0x6c, 0x86, 0x99, 0x69, 0x5b, 0xd4, 0x37, 0x92, 0x7e, 0x3a, 0xbe, 0xf3, 0xbe, 0x51, 0x5f,
	0x73, 0x75, 0x3c, 0x4d, 0x97, 0xf8, 0x41, 0x53, 0x86, 0x99, 0x8c, 0x3c, 0xfd, 0x78, 0x3c, 0xd5,
	0x01, 0x87, 0x0f, 0x87, 0x6b, 0x9d, 0xe4, 0x73, 0xad, 0xae, 0x47, 0x19, 0x71, 0x4d, 0xab, 0x23,
	0x45, 0x3f, 0x18, 0x29, 0xca, 0xcc, 0x1e, 0xd1, 0x1d, 0xec, 0x32, 0x93, 0x57, 0xe1, 0x5c, 0xe3,
	0x5d, 0xa9, 0x21, 0x4e, 0x07, 0x5e, 0x3b, 0x67, 0x78, 0xae, 0x28, 0x94, 0xe4, 0xdf, 0x1d, 0xe4,
	0x93, 0x9e, 0xc3, 0xce, 0x24, 0x73, 0x69, 0x90, 0xd9, 0x36, 0x49, 0xd7, 0xd0, 0x7b, 0x98, 0x1e,
	0x49, 0x89, 0xfb, 0x83, 0x12, 0x3c, 0x0e, 0xca, 0x70, 0xcf, 0x19, 0xe5, 0xff, 0xd4, 0xc5, 0x8e,
	0x43, 0x5c, 0xd9, 0xa7, 0xcc, 0x3f, 0x67, 0x41, 0xad, 0xf4, 0x1c, 0xdb, 0x65, 0xc4, 0x28, 0x61,
	0x86, 0x2b, 0x56, 0xdb, 0x46, 0x2a, 0x44, 0xe9, 0x71, 0x37, 0xa5, 0x2c, 0x29, 0xcb, 0x09, 0x8d,
	0x7f, 0xa2, 0x0f, 0x60, 0xc1, 0x20, 0x94, 0x99, 0x96, 0x88, 0x5d, 0x67, 0xf8, 0xa0, 0x4b, 0x74,
	0xd3, 0x48, 0x45, 0x84, 0x08, 0x0a, 0xf1, 0x9a, 0x9c, 0x55, 0x31, 0xd0, 0x3a, 0xdc, 0xbb, 0xa8,
	0x61, 0x10, 0xda, 0x72, 0x4d, 0x87, 0x53, 0x52, 0x20, 0x54, 0xef, 0x0e, 0xaa, 0x96, 0xce, 0x45,
	0x50, 0x1b, 0x20, 0xd0, 0x6b, 0xd3, 0x54, 0x74, 0x29, 0xba, 0x9c, 0xcc, 0x6f, 0x66, 0xc7, 0x82,
	0x67, 0x76, 0x30, 0xa9, 0xac, 0xb4, 0xde, 0x36, 0x2d, 0xd1, 0x22, 0x2d, 0xc1, 0x24, 0x81, 0xa2,
	0xc7, 0xb0, 0xe8, 0x51, 0xe2, 0x72, 0x37, 0xa6, 0x45, 0x0c, 0xbd, 0xed, 0x59, 0x2d, 0x01, 0xe6,
	0xd4, 0xc4, 0x52, 0x74, 0x39, 0xa1, 0x2d, 0x70, 0x6e, 0xc9, 0x67, 0x6e, 0x04, 0xbc, 0xf4, 0x5f,
	0xa3, 0x90, 0xdc, 0xe0, 0x0d, 0x69, 0xb4, 0x0e, 0x49, 0x0f, 0xa3, 0x7b, 0x00, 0x7e, 0x7f, 0x2c,
	0xdc, 0x23, 0xb2, 0x78, 0x09, 0x41, 0xa9, 0xe2, 0x1e, 0x41, 0xfb, 0x30, 0xc1, 0xce, 0x1c, 0x22,
	0x4a, 0x36, 0x9b, 0x7f, 0x7e, 0xdd, 0x34, 0x42, 0x1e, 0xb3, 0xcd, 0x33, 0x87, 0x68, 0xc2, 0x2a,
	0xba, 0x0f, 0x49, 0x93, 0xea, 0x2e, 0x71, 0x08, 0x66, 0xc4, 0x48, 0x45, 0x97, 0x94, 0xe5, 0xb8,
	0x06, 0x26, 0xd5, 0x24, 0x05, 0x2d, 0x41, 0x32, 0x5c, 0xfd, 0x09, 0x11, 0x5e, 0x98, 0x84, 0xf6,
	0x21, 0x46, 0x85, 0xdd, 0xd4, 0xe4, 0x92, 0xb2, 0x9c, 0xcc, 0x97, 0xae, 0x1b, 0xa2, 0x46, 0x5a,
	0xb6, 0x2b, 0x63, 0xd4, 0xa4, 0xcd, 0xcc, 0x6f, 0x15, 0x98, 0xe0, 0xf1, 0xa2, 0x05, 0x50, 0x9b,
	0x2f, 0xea, 0x65, 0x7d, 0xb7, 0xda, 0xa8, 0x97, 0x8b, 0x95, 0x8d, 0x4a, 0xb9, 0xa4, 0xfe, 0x1f,
	0x02, 0x88, 0x35, 0x9a, 0x5a, 0xa5, 0xba, 0xa9, 0x2a, 0x28, 0x09, 0x53, 0x95, 0x6a, 0xb3, 0xbc,
	0x59, 0xd6, 0xd4, 0x08, 0x4a, 0xc0, 0xe4, 0xc6, 0x56, 0xad, 0xd0, 0x54, 0xa3, 0x5c, 0x46, 0x2b,
	0x17, 0x6b, 0x5a, 0x49, 0x9d, 0xe0, 0xe4, 0xf5, 0x17, 0xcd, 0x72, 0x43, 0x9d, 0xe4, 0xe2, 0xeb,
	0xb5, 0xda, 0x56, 0xb9, 0x50, 0x55, 0x63, 0x68, 0x06, 0x12, 0xcd, 0xca, 0x76, 0xb9, 0xd1, 0x2c,
	0x6c, 0xd7, 0xd5, 0x29, 0x14, 0x87, 0x89, 0x52, 0xa1, 0x59, 0x56, 0xe3, 0xfc, 0x8b, 0x33, 0xd4,
	0x04, 0x9a, 0x86, 0x38, 0xa7, 0x89, 0x13, 0x70, 0xed, 0xea, 0xee, 0x76, 0x59, 0xab, 0x14, 0xd5,
	0x64, 0xfa, 0x08, 0xa6, 0xc3, 0xc1, 0xa3, 0x9f, 0x42, 0x4c, 0x34, 0x90, 0xa6, 0x14, 0x01, 0xbe,
	0xe2, 0x5b, 0xe8, 0x9a, 0x26, 0x4d, 0xa6, 0xbf, 0x8a, 0xc1, 0xdc, 0x00, 0x28, 0xd1, 0x1d, 0x88,
	0xf7, 0xef, 0x96, 0x8f, 0xa0, 0x29, 0x26, 0x2f, 0xd4, 0x7d, 0x48, 0xfa, 0x2f, 0x9e, 0xee, 0xb9,
	0x26, 0x4d, 0x45, 0x04, 0x32, 0xc1, 0x27, 0xed, 0xba, 0x26, 0x45, 0x7b, 0x10, 0x6b, 0xdb, 0x6e,
	0x0f, 0x33, 0xd1, 0xfd, 0xd9, 0xfc, 0xc7, 0xd7, 0x0e, 0x56, 0x58, 0xd1, 0xa4, 0x35, 0xf4, 0x3e,
	0xcc, 0xf5, 0xf0, 0x4b, 0xfd, 0x00, 0x1b, 0xba, 0x2b, 0x8a, 0x43, 0x05, 0x7a, 0x26, 0xb5, 0x99,
	0x1e, 0x7e, 0xb9, 0x8e, 0x0d, 0xbf, 0x62, 0x14, 0xed, 0x43, 0x9c, 0x58, 0x2d, 0xdb, 0x30, 0xad,
	0x8e, 0x40, 0xd0, 0x6c, 0xfe, 0xd3, 0xeb, 0x46, 0x50, 0x96, 0x76, 0xb4, 0xbe, 0x45, 0x44, 0x21,
	0xd9, 0xa2, 0x27, 0xba, 0xed, 0xf8, 0x17, 0x33, 0x26, 0x20, 0xaa, 0xbd, 0xa5, 0xc7, 0x20, 0x5b,
	0xa4, 0x27, 0x35, 0xdf, 0xb2, 0x06, 0xad, 0xfe, 0x77, 0xe8, 0x4a, 0x4c, 0xbd, 0xfd, 0x2b, 0x91,
	0xfe, 0x5d, 0x04, 0xe0, 0xdc, 0x31, 0x2a, 0xc3, 0x9c, 0xff, 0x7e, 0x18, 0xa4, 0x6b, 0xf6, 0x4c,
	0x46, 0x5c, 0x01, 0x81, 0x64, 0xfe, 0x9d, 0xc0, 0x6b, 0xf0, 0x88, 0x67, 0x1b, 0x8c, 0x0f, 0xa5,
	0x3d, 0xdc, 0xf5, 0x88, 0x36, 0x2b, 0x94, 0x4a, 0x81, 0x0e, 0xaa, 0xc2, 0x2d, 0xdc, 0xed, 0xda,
	0xa7, 0xfa, 0xb1, 0x67, 0x33, 0x62, 0xe8, 0x16, 0x39, 0xed, 0x9a, 0x16, 0xa1, 0xe2, 0xe1, 0x49,
	0xe6, 0xd3, 0x17, 0x8c, 0xad, 0xdb, 0x76, 0xd7, 0x37, 0xf5, 0xff, 0x42, 0x71, 0x47, 0xe8, 0x55,
	0xa5, 0x1a, 0x5a, 0x03, 0x10, 0x96, 0xf4, 0xd6, 0x21, 0x76, 0x05, 0xb4, 0xae, 0x8a, 0x28, 0x21,
	0xe4, 0x8b, 0x87, 0xd8, 0x45, 0x9b, 0x30, 0x4f, 0x8f, 0x4c, 0x47, 0xef, 0x12, 0xcc, 0xbb, 0xa8,
	0xbb, 0xf6, 0xa9, 0x8f, 0x9e, 0x64, 0xfe, 0xee, 0x05, 0x1b, 0x15, 0x8b, 0x3d, 0x79, 0xec, 0x9b,
	0x98, 0xe3, 0x5a, 0x5b, 0xbe, 0x92, 0x66, 0x9f, 0xd2, 0xcc, 0x2f, 0x20, 0xe6, 0xc3, 0x12, 0x2d,
	0x02, 0xda, 0xa8, 0x69, 0xdb, 0x85, 0xe6, 0xc0, 0x0b, 0x32, 0x05, 0xd1, 0x62, 0x63, 0x4f, 0x55,
	0xf8, 0x4d, 0xff, 0xac, 0x51, 0xab, 0xaa, 0x11, 0xfe, 0x55, 0xd8, 0xd3, 0x6a, 0x6a, 0x94, 0xdf,
	0x79, 0xff, 0xe9, 0xa8, 0xd4, 0xd4, 0x09, 0x7e, 0x2a, 0xd6, 0xb6, 0x76, 0xb7, 0xab, 0x95, 0x9a,
	0x3a, 0xc9, 0x9f, 0x8c, 0x62, 0xa1, 0x5e, 0x28, 0x56, 0x9a, 0x35, 0x4d, 0x8d, 0xf1, 0x07, 0xa1,
	0x5e, 0xd0, 0x76, 0x76, 0xcb, 0x4d, 0x75, 0x8a, 0x1b, 0xad, 0x69, 0x45, 0x35, 0x9e, 0xf9, 0x18,
	0xe2, 0x01, 0x28, 0x51, 0x0a, 0x16, 0xca, 0xd5, 0x62, 0xad, 0x54, 0xa9, 0x6e, 0x0e, 0xc4, 0x30,
	0x0b, 0x50, 0x69, 0xd4, 0xf4, 0xa7, 0x4f, 0x7f, 0xb8, 0xaa, 0xaf, 0xf8, 0xa1, 0xec, 0x36, 0x37,
	0x9e, 0xaa, 0x91, 0xcc, 0x1f, 0x14, 0x48, 0xed, 0x3a, 0x06, 0x66, 0xa4, 0x29, 0x71, 0xa2, 0x79,
	0x96, 0x46, 0x8e, 0x3d, 0x42, 0x19, 0xda, 0x85, 0xe9, 0x00, 0x3d, 0xba, 0xeb, 0x59, 0xb2, 0xed,
	0xf9, 0x31, 0xc1, 0x16, 0x36, 0x98, 0x64, 0xe7, 0x07, 0xb4, 0x06, 0x49, 0x4f, 0xb8, 0x14, 0x1b,
	0xc3, 0xc8, 0xfe, 0x8b, 0xb7, 0x69, 0x1b, 0xd3, 0x23, 0x0d, 0x7c, 0x71, 0xfe, 0x9d, 0xf9, 0x8d,
	0x02, 0xf7, 0xb6, 0xec, 0x4e, 0xc8, 0xf8, 0x36, 0xa1, 0x14, 0x77, 0x08, 0x0d, 0xa2, 0x46, 0x30,
	0x11, 0x9a, 0x74, 0xe2, 0x1b, 0xb5, 0x60, 0xbe, 0x9f, 0x49, 0x4f, 0xca, 0x8b, 0xa7, 0x2a, 0x99,
	0x7f, 0xf2, 0x86, 0xe9, 0x48, 0x77, 0x9a, 0xca, 0x5e, 0x27, 0xd0, 0xcc, 0x1f, 0x15, 0x48, 0x35,
	0x18, 0x76, 0xd9, 0xba, 0xd9, 0xd9, 0xe1, 0x36, 0x3e, 0xb3, 0x0f, 0x2e, 0x8d, 0x6a, 0x1f, 0x66,
	0x4c, 0x79, 0x23, 0x75, 0xee, 0x4e, 0x46, 0xf4, 0xe1, 0x35, 0x6f, 0xb3, 0x36, 0x6d, 0x86, 0x28,
	0xe8, 0x21, 0xa8, 0x62, 0x7b, 0x68, 0xb9, 0xc4, 0x20, 0x16, 0x33, 0x71, 0x97, 0x8a, 0x6b, 0x32,
	0xad, 0xcd, 0x71, 0x7a, 0xf1, 0x9c, 0x9c, 0x79, 0x1f, 0xd4, 0x0d, 0xd3, 0x32, 0xe9, 0x61, 0xa8,
	0xf9, 0x43, 0x02, 0xce, 0x7c, 0x1f, 0x6e, 0x6d, 0x12, 0x16, 0xd2, 0x1c, 0x14, 0x8e, 0x86, 0x84,
	0x3f, 0x85, 0x64, 0x48, 0xb2, 0x2f, 0x12, 0x09, 0x15, 0xe0, 0x1e, 0x00, 0xf6, 0xd8, 0xa1, 0xce,
	0xec, 0x23, 0x62, 0x05, 0xab, 0x09, 0xa7, 0x34, 0x39, 0x81, 0x83, 0xf3, 0x41, 0xd1, 0xe5, 0x7b,
	0x02, 0x4f, 0xa8, 0x21, 0x46, 0x4a, 0x68, 0x53, 0x92, 0xbe, 0x17, 0x21, 0xe6, 0x60, 0x97, 0x58,
	0x4c, 0x1a, 0x90, 0x27, 0x74, 0x0c, 0x8b, 0xbc, 0x62, 0xba, 0x9c, 0x4e, 0x46, 0x5f, 0x51, 0x22,
	0x6e, 0x6d, 0xcc, 0x32, 0x0f, 0xf5, 0xbd, 0x60, 0x0c, 0xa1, 0x66, 0xbe, 0x55, 0xe0, 0x81, 0x7f,
	0x9b, 0x2e, 0x0b, 0x78, 0x74, 0x60, 0xca, 0x77, 0x14, 0xd8, 0xcd, 0xae, 0xdc, 0x87, 0xf0, 0xa0,
	0x44, 0xba, 0xe4, 0xf2, 0xa4, 0x86, 0xc1, 0xe5, 0x31, 0xbc, 0xbb, 0x49, 0xd8, 0x9b, 0x6a, 0x9d,
	0xc0, 0xd2, 0x96, 0x49, 0x87, 0xaa, 0xd1, 0xab, 0x7a, 0x7e, 0x0f, 0xc0, 0xc1, 0x1d, 0x22, 0x01,
	0xe5, 0x43, 0x2d, 0xc1, 0x29, 0x02, 0x50, 0xe8, 0x2e, 0x88, 0x83, 0x4e, 0xcd, 0x2f, 0x7d, 0xac,
	0x4e, 0x6a, 0x71, 0x4e, 0x68, 0x98, 0x5f, 0x92, 0xcc, 0x9f, 0x14, 0x78, 0x70, 0x89, 0x63, 0xea,
	0xd8, 0x16, 0x25, 0x88, 0xc2, 0xed, 0xe1, 0xcd, 0x0b, 0x76, 0xb1, 0x1b, 0x75, 0xef, 0xd6, 0xb0,
	0xee, 0x51, 0xbe, 0xea, 0x58, 0xe4, 0x25, 0xd3, 0x2f, 0xe4, 0x36, 0xc3, 0xc9, 0xf5, 0x20, 0xbf,
	0xcc, 0x7f, 0x22, 0xb0, 0x30, 0xcc, 0x6e, 0xbf, 0xce, 0xb7, 0x42, 0x97, 0x4f, 0x83, 0x64, 0x28,
	0x13, 0x89, 0xbd, 0x95, 0x37, 0x8e, 0x5e, 0x83, 0xf3, 0x98, 0xd1, 0x2a, 0xdc, 0x09, 0x4f, 0x0c,
	0xdd, 0xf1, 0x0e, 0xa8, 0x77, 0xa0, 0x33, 0xdb, 0x31, 0x5b, 0xa9, 0x19, 0xe1, 0x7c, 0x31, 0x34,
	0x0a, 0xea, 0x82, 0xdd, 0xe4, 0x5c, 0x54, 0x80, 0x39, 0xae, 0x21, 0x7e, 0xb0, 0xda, 0xed, 0x36,
	0x25, 0x2c, 0xa5, 0x8a, 0x90, 0xee, 0x5c, 0x80, 0x69, 0x49, 0xfe, 0x56, 0xd5, 0x66, 0x5c, 0xcf,
	0x6a, 0x9a, 0x3d, 0x52, 0x13, 0xf2, 0xe8, 0x7b, 0x30, 0x43, 0x3d, 0x87, 0x3f, 0x81, 0x3a, 0xe9,
	0x61, 0xb3, 0x9b, 0x5a, 0x14, 0x1e, 0xa7, 0x25, 0xb1, 0xcc, 0x69, 0x28, 0x0d, 0x71, 0xc3, 0xa4,
	0x7c, 0xcf, 0x32, 0xc4, 0x3a, 0x18, 0xd7, 0xfa, 0x67, 0xfe, 0x83, 0x4b, 0xca, 0x12, 0x43, 0xef,
	0xda, 0x2d, 0xff, 0x37, 0xa2, 0x69, 0xd0, 0xd4, 0x6d, 0xff, 0x07, 0x57, 0x9f, 0xbb, 0x25, 0x99,
	0x15, 0x83, 0xe6, 0xbf, 0x9e, 0x87, 0xf9, 0xf3, 0x7a, 0x34, 0x88, 0x7b, 0x62, 0xb6, 0x08, 0xfa,
	0x97, 0x02, 0xf3, 0x17, 0x26, 0x2b, 0xfa, 0x64, 0xcc, 0xfa, 0x8e, 0x9a, 0xc9, 0xe9, 0x6b, 0x4c,
	0xdf, 0xcc, 0xcf, 0x7e, 0xf9, 0xed, 0x3f, 0x7e, 0x15, 0xf9, 0x3c, 0xbf, 0x99, 0x3b, 0x59, 0xc9,
	0xfd, 0x3c, 0xdc, 0xa0, 0x2c, 0x47, 0xc2, 0x47, 0x8e, 0x6b, 0x7f, 0x41, 0x5a, 0x8c, 0xe6, 0x1e,
	0xe5, 0x82, 0xa4, 0xf9, 0x77, 0x20, 0x58, 0xb4, 0xad, 0xb6, 0xd9, 0xe1, 0x14, 0xd7, 0xe3, 0x8c,
	0x57, 0xcf, 0x5e, 0x5b, 0x0b, 0xd0, 0x37, 0x0a, 0x2c, 0x0e, 0x1f, 0xc9, 0x68, 0xdc, 0xc5, 0xf4,
	0xd2, 0x89, 0x9e, 0x5e, 0xbc, 0x80, 0x80, 0x72, 0xcf, 0x61, 0x67, 0x99, 0x1d, 0x91, 0xd7, 0x8f,
	0x33, 0x1b, 0x22, 0xaf, 0xeb, 0xa5, 0xd2, 0xb5, 0x3b, 0x81, 0xbb, 0x67, 0xca, 0x23, 0xf4, 0x67,
	0x05, 0xe6, 0x2f, 0xcc, 0xf0, 0xb1, 0xbb, 0x36, 0x6a, 0xfa, 0x8f, 0xcc, 0xe0, 0x73, 0x91, 0xc1,
	0x4e, 0x66, 0xeb, 0x06, 0x19, 0xd0, 0x41, 0xa7, 0x3c, 0x8f, 0x6f, 0x14, 0x98, 0x7d, 0x7d, 0x54,
	0xa3, 0x1f, 0x8d, 0x99, 0xc4, 0xd0, 0x09, 0x3f, 0x36, 0xee, 0xc2, 0x6b, 0x45, 0x59, 0x64, 0xf7,
	0x09, 0xfa, 0xe8, 0xca, 0xec, 0xce, 0x9f, 0x10, 0x7e, 0x0a, 0x6d, 0x2c, 0xb9, 0x47, 0xaf, 0xd0,
	0xef, 0x15, 0x48, 0xf4, 0xd7, 0x13, 0x34, 0xee, 0x76, 0x34, 0xb8, 0xd0, 0x8c, 0xec, 0x41, 0x4d,
	0x44, 0x59, 0xc9, 0x94, 0x6e, 0xd0, 0x83, 0x76, 0xe0, 0x8c, 0xd7, 0xfe, 0xbf, 0x0a, 0xa4, 0x47,
	0xaf, 0x2d, 0xe8, 0xf9, 0xf8, 0x95, 0xbc, 0x7c, 0x91, 0x48, 0xdf, 0x64, 0xd4, 0x64, 0x5e, 0x88,
	0xb4, 0x1b, 0x99, 0x55, 0x91, 0xb6, 0x3f, 0x3f, 0x47, 0x24, 0xfe, 0x2a, 0x37, 0x74, 0x2c, 0x3d,
	0x1b, 0xb1, 0xc6, 0xa0, 0x5f, 0x47, 0x20, 0x3d, 0x7a, 0x0d, 0x1a, 0xbb, 0x00, 0x57, 0x6e, 0x52,
	0x37, 0x2b, 0x80, 0x23, 0x0a, 0xf0, 0x45, 0xbe, 0x2e, 0x0a, 0x30, 0x3c, 0x95, 0xec, 0x78, 0xa0,
	0x0d, 0x15, 0x85, 0xa3, 0x61, 0x54, 0x5d, 0xbe, 0x56, 0x20, 0x3d, 0x7a, 0x93, 0x1a, 0xbb, 0x2e,
	0x57, 0x2e, 0x63, 0x23, 0xa1, 0x5e, 0x10, 0x29, 0xaf, 0x3d, 0x5a, 0x7d, 0x83, 0x0b, 0xf9, 0x7a,
	0x6e, 0xe8, 0x6f, 0x0a, 0xdc, 0x1e, 0xb1, 0xd4, 0xa1, 0xf2, 0xf8, 0x2f, 0xcc, 0x77, 0xd6, 0x55,
	0x99, 0x22, 0xba, 0x41, 0x8a, 0xff, 0x56, 0xe0, 0xce, 0xc8, 0x45, 0x10, 0x8d, 0xfb, 0x87, 0xde,
	0xab, 0x76, 0xd8, 0xf4, 0xf3, 0x9b, 0x1b, 0xf2, 0x77, 0xd2, 0x81, 0x9c, 0xaf, 0x73, 0x95, 0xd7,
	0xff, 0xae, 0xc0, 0xc3, 0x96, 0xdd, 0x1b, 0x2f, 0xa4, 0xf5, 0xb9, 0xf3, 0x78, 0xea, 0x1c, 0x61,
	0x75, 0xe5, 0x27, 0x3b, 0x52, 0xb3, 0x63, 0x77, 0xb1, 0xd5, 0xc9, 0xda, 0x6e, 0x27, 0xd7, 0x21,
	0x96, 0xc0, 0x5f, 0xce, 0x67, 0x61, 0xc7, 0xa4, 0x57, 0xfc, 0x0b, 0x64, 0x2d, 0x7c, 0xfe, 0x2a,
	0xf2, 0xde, 0xa6, 0x6f, 0xb3, 0x28, 0xa2, 0x09, 0x46, 0x9c, 0xe8, 0x7b, 0xb0, 0x2d, 0x64, 0xf7,
	0x56, 0xfe, 0x12, 0xc8, 0xed, 0x0b, 0xb9, 0xfd, 0x40, 0x6e, 0x3f, 0x2c, 0xb7, 0xbf, 0xb7, 0x72,
	0x10, 0x13, 0xd1, 0xfc, 0xe0, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x3f, 0x03, 0x63, 0x81,
	0x1a, 0x00, 0x00,
}
