// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/bigquery/datatransfer/v1/transfer.proto

package datatransfer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DEPRECATED. Represents data transfer type.
type TransferType int32 // Deprecated: Do not use.
const (
	// Invalid or Unknown transfer type placeholder.
	TransferType_TRANSFER_TYPE_UNSPECIFIED TransferType = 0
	// Batch data transfer.
	TransferType_BATCH TransferType = 1
	// Streaming data transfer. Streaming data source currently doesn't
	// support multiple transfer configs per project.
	TransferType_STREAMING TransferType = 2
)

var TransferType_name = map[int32]string{
	0: "TRANSFER_TYPE_UNSPECIFIED",
	1: "BATCH",
	2: "STREAMING",
}

var TransferType_value = map[string]int32{
	"TRANSFER_TYPE_UNSPECIFIED": 0,
	"BATCH":                     1,
	"STREAMING":                 2,
}

func (x TransferType) String() string {
	return proto.EnumName(TransferType_name, int32(x))
}

func (TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{0}
}

// Represents data transfer run state.
type TransferState int32

const (
	// State placeholder.
	TransferState_TRANSFER_STATE_UNSPECIFIED TransferState = 0
	// Data transfer is scheduled and is waiting to be picked up by
	// data transfer backend.
	TransferState_PENDING TransferState = 2
	// Data transfer is in progress.
	TransferState_RUNNING TransferState = 3
	// Data transfer completed successfully.
	TransferState_SUCCEEDED TransferState = 4
	// Data transfer failed.
	TransferState_FAILED TransferState = 5
	// Data transfer is cancelled.
	TransferState_CANCELLED TransferState = 6
)

var TransferState_name = map[int32]string{
	0: "TRANSFER_STATE_UNSPECIFIED",
	2: "PENDING",
	3: "RUNNING",
	4: "SUCCEEDED",
	5: "FAILED",
	6: "CANCELLED",
}

var TransferState_value = map[string]int32{
	"TRANSFER_STATE_UNSPECIFIED": 0,
	"PENDING":                    2,
	"RUNNING":                    3,
	"SUCCEEDED":                  4,
	"FAILED":                     5,
	"CANCELLED":                  6,
}

func (x TransferState) String() string {
	return proto.EnumName(TransferState_name, int32(x))
}

func (TransferState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{1}
}

// Represents data transfer user facing message severity.
type TransferMessage_MessageSeverity int32

const (
	// No severity specified.
	TransferMessage_MESSAGE_SEVERITY_UNSPECIFIED TransferMessage_MessageSeverity = 0
	// Informational message.
	TransferMessage_INFO TransferMessage_MessageSeverity = 1
	// Warning message.
	TransferMessage_WARNING TransferMessage_MessageSeverity = 2
	// Error message.
	TransferMessage_ERROR TransferMessage_MessageSeverity = 3
	// Debug message.
	TransferMessage_DEBUG TransferMessage_MessageSeverity = 4
)

var TransferMessage_MessageSeverity_name = map[int32]string{
	0: "MESSAGE_SEVERITY_UNSPECIFIED",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
	4: "DEBUG",
}

var TransferMessage_MessageSeverity_value = map[string]int32{
	"MESSAGE_SEVERITY_UNSPECIFIED": 0,
	"INFO":                         1,
	"WARNING":                      2,
	"ERROR":                        3,
	"DEBUG":                        4,
}

func (x TransferMessage_MessageSeverity) String() string {
	return proto.EnumName(TransferMessage_MessageSeverity_name, int32(x))
}

func (TransferMessage_MessageSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{4, 0}
}

// Represents preferences for sending email notifications for transfer run
// events.
type EmailPreferences struct {
	// If true, email notifications will be sent on transfer run failures.
	EnableFailureEmail   bool     `protobuf:"varint,1,opt,name=enable_failure_email,json=enableFailureEmail,proto3" json:"enable_failure_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailPreferences) Reset()         { *m = EmailPreferences{} }
func (m *EmailPreferences) String() string { return proto.CompactTextString(m) }
func (*EmailPreferences) ProtoMessage()    {}
func (*EmailPreferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{0}
}

func (m *EmailPreferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailPreferences.Unmarshal(m, b)
}
func (m *EmailPreferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailPreferences.Marshal(b, m, deterministic)
}
func (m *EmailPreferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailPreferences.Merge(m, src)
}
func (m *EmailPreferences) XXX_Size() int {
	return xxx_messageInfo_EmailPreferences.Size(m)
}
func (m *EmailPreferences) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailPreferences.DiscardUnknown(m)
}

var xxx_messageInfo_EmailPreferences proto.InternalMessageInfo

func (m *EmailPreferences) GetEnableFailureEmail() bool {
	if m != nil {
		return m.EnableFailureEmail
	}
	return false
}

// Options customizing the data transfer schedule.
type ScheduleOptions struct {
	// If true, automatic scheduling of data transfer runs for this configuration
	// will be disabled. The runs can be started on ad-hoc basis using
	// StartManualTransferRuns API. When automatic scheduling is disabled, the
	// TransferConfig.schedule field will be ignored.
	DisableAutoScheduling bool `protobuf:"varint,3,opt,name=disable_auto_scheduling,json=disableAutoScheduling,proto3" json:"disable_auto_scheduling,omitempty"`
	// Specifies time to start scheduling transfer runs. The first run will be
	// scheduled at or after the start time according to a recurrence pattern
	// defined in the schedule string. The start time can be changed at any
	// moment. The time when a data transfer can be trigerred manually is not
	// limited by this option.
	StartTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Defines time to stop scheduling transfer runs. A transfer run cannot be
	// scheduled at or after the end time. The end time can be changed at any
	// moment. The time when a data transfer can be trigerred manually is not
	// limited by this option.
	EndTime              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ScheduleOptions) Reset()         { *m = ScheduleOptions{} }
func (m *ScheduleOptions) String() string { return proto.CompactTextString(m) }
func (*ScheduleOptions) ProtoMessage()    {}
func (*ScheduleOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{1}
}

func (m *ScheduleOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleOptions.Unmarshal(m, b)
}
func (m *ScheduleOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleOptions.Marshal(b, m, deterministic)
}
func (m *ScheduleOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleOptions.Merge(m, src)
}
func (m *ScheduleOptions) XXX_Size() int {
	return xxx_messageInfo_ScheduleOptions.Size(m)
}
func (m *ScheduleOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleOptions proto.InternalMessageInfo

func (m *ScheduleOptions) GetDisableAutoScheduling() bool {
	if m != nil {
		return m.DisableAutoScheduling
	}
	return false
}

func (m *ScheduleOptions) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ScheduleOptions) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

// Represents a data transfer configuration. A transfer configuration
// contains all metadata needed to perform a data transfer. For example,
// `destination_dataset_id` specifies where data should be stored.
// When a new transfer configuration is created, the specified
// `destination_dataset_id` is created when needed and shared with the
// appropriate data source service account.
type TransferConfig struct {
	// The resource name of the transfer config.
	// Transfer config names have the form of
	// `projects/{project_id}/locations/{region}/transferConfigs/{config_id}`.
	// The name is automatically generated based on the config_id specified in
	// CreateTransferConfigRequest along with project_id and region. If config_id
	// is not provided, usually a uuid, even though it is not guaranteed or
	// required, will be generated for config_id.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The desination of the transfer config.
	//
	// Types that are valid to be assigned to Destination:
	//	*TransferConfig_DestinationDatasetId
	Destination isTransferConfig_Destination `protobuf_oneof:"destination"`
	// User specified display name for the data transfer.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Data source id. Cannot be changed once data transfer is created.
	DataSourceId string `protobuf:"bytes,5,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	// Data transfer specific parameters.
	Params *_struct.Struct `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty"`
	// Data transfer schedule.
	// If the data source does not support a custom schedule, this should be
	// empty. If it is empty, the default value for the data source will be
	// used.
	// The specified times are in UTC.
	// Examples of valid format:
	// `1st,3rd monday of month 15:30`,
	// `every wed,fri of jan,jun 13:15`, and
	// `first sunday of quarter 00:00`.
	// See more explanation about the format here:
	// https://cloud.google.com/appengine/docs/flexible/python/scheduling-jobs-with-cron-yaml#the_schedule_format
	// NOTE: the granularity should be at least 8 hours, or less frequent.
	Schedule string `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Options customizing the data transfer schedule.
	ScheduleOptions *ScheduleOptions `protobuf:"bytes,24,opt,name=schedule_options,json=scheduleOptions,proto3" json:"schedule_options,omitempty"`
	// The number of days to look back to automatically refresh the data.
	// For example, if `data_refresh_window_days = 10`, then every day
	// BigQuery reingests data for [today-10, today-1], rather than ingesting data
	// for just [today-1].
	// Only valid if the data source supports the feature. Set the value to  0
	// to use the default value.
	DataRefreshWindowDays int32 `protobuf:"varint,12,opt,name=data_refresh_window_days,json=dataRefreshWindowDays,proto3" json:"data_refresh_window_days,omitempty"`
	// Is this config disabled. When set to true, no runs are scheduled
	// for a given transfer.
	Disabled bool `protobuf:"varint,13,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Output only. Data transfer modification time. Ignored by server on input.
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Output only. Next time when data transfer will run.
	NextRunTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`
	// Output only. State of the most recently updated transfer run.
	State TransferState `protobuf:"varint,10,opt,name=state,proto3,enum=google.cloud.bigquery.datatransfer.v1.TransferState" json:"state,omitempty"`
	// Deprecated. Unique ID of the user on whose behalf transfer is done.
	UserId int64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Output only. Region in which BigQuery dataset is located.
	DatasetRegion string `protobuf:"bytes,14,opt,name=dataset_region,json=datasetRegion,proto3" json:"dataset_region,omitempty"`
	// Pub/Sub topic where notifications will be sent after transfer runs
	// associated with this transfer config finish.
	NotificationPubsubTopic string `protobuf:"bytes,15,opt,name=notification_pubsub_topic,json=notificationPubsubTopic,proto3" json:"notification_pubsub_topic,omitempty"`
	// Email notifications will be sent according to these preferences
	// to the email address of the user who owns this transfer config.
	EmailPreferences *EmailPreferences `protobuf:"bytes,18,opt,name=email_preferences,json=emailPreferences,proto3" json:"email_preferences,omitempty"`
	// A unique identifier used for identifying a transfer setup stored on
	// external partner side. The token is opaque to DTS and can only be
	// interpreted by partner. Partner data source should create a mapping between
	// the config id and the token to validate that a transfer config/run is
	// legitimate.
	PartnerToken string `protobuf:"bytes,22,opt,name=partner_token,json=partnerToken,proto3" json:"partner_token,omitempty"`
	// Transfer settings managed by partner data sources. It is stored as
	// key-value pairs and used for DTS UI display purpose only. Two reasons we
	// don't want to store them together with 'params' are:
	//  - The connection info is provided by partner and not editable in DTS UI
	//    which is different from the immutable parameter. It will be confusing to
	//    add another boolean to DataSourceParameter to differentiate them.
	//  - The connection info can be any arbitrary key-value pairs. Adding them to
	//    params fields requires partner to provide definition for them in data
	//    source definition. It will be friendlier to avoid that for partners.
	PartnerConnectionInfo *_struct.Struct `protobuf:"bytes,23,opt,name=partner_connection_info,json=partnerConnectionInfo,proto3" json:"partner_connection_info,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}        `json:"-"`
	XXX_unrecognized      []byte          `json:"-"`
	XXX_sizecache         int32           `json:"-"`
}

func (m *TransferConfig) Reset()         { *m = TransferConfig{} }
func (m *TransferConfig) String() string { return proto.CompactTextString(m) }
func (*TransferConfig) ProtoMessage()    {}
func (*TransferConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{2}
}

func (m *TransferConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferConfig.Unmarshal(m, b)
}
func (m *TransferConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferConfig.Marshal(b, m, deterministic)
}
func (m *TransferConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferConfig.Merge(m, src)
}
func (m *TransferConfig) XXX_Size() int {
	return xxx_messageInfo_TransferConfig.Size(m)
}
func (m *TransferConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TransferConfig proto.InternalMessageInfo

func (m *TransferConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isTransferConfig_Destination interface {
	isTransferConfig_Destination()
}

type TransferConfig_DestinationDatasetId struct {
	DestinationDatasetId string `protobuf:"bytes,2,opt,name=destination_dataset_id,json=destinationDatasetId,proto3,oneof"`
}

func (*TransferConfig_DestinationDatasetId) isTransferConfig_Destination() {}

func (m *TransferConfig) GetDestination() isTransferConfig_Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *TransferConfig) GetDestinationDatasetId() string {
	if x, ok := m.GetDestination().(*TransferConfig_DestinationDatasetId); ok {
		return x.DestinationDatasetId
	}
	return ""
}

func (m *TransferConfig) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *TransferConfig) GetDataSourceId() string {
	if m != nil {
		return m.DataSourceId
	}
	return ""
}

func (m *TransferConfig) GetParams() *_struct.Struct {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *TransferConfig) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func (m *TransferConfig) GetScheduleOptions() *ScheduleOptions {
	if m != nil {
		return m.ScheduleOptions
	}
	return nil
}

func (m *TransferConfig) GetDataRefreshWindowDays() int32 {
	if m != nil {
		return m.DataRefreshWindowDays
	}
	return 0
}

func (m *TransferConfig) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *TransferConfig) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *TransferConfig) GetNextRunTime() *timestamp.Timestamp {
	if m != nil {
		return m.NextRunTime
	}
	return nil
}

func (m *TransferConfig) GetState() TransferState {
	if m != nil {
		return m.State
	}
	return TransferState_TRANSFER_STATE_UNSPECIFIED
}

func (m *TransferConfig) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TransferConfig) GetDatasetRegion() string {
	if m != nil {
		return m.DatasetRegion
	}
	return ""
}

func (m *TransferConfig) GetNotificationPubsubTopic() string {
	if m != nil {
		return m.NotificationPubsubTopic
	}
	return ""
}

func (m *TransferConfig) GetEmailPreferences() *EmailPreferences {
	if m != nil {
		return m.EmailPreferences
	}
	return nil
}

func (m *TransferConfig) GetPartnerToken() string {
	if m != nil {
		return m.PartnerToken
	}
	return ""
}

func (m *TransferConfig) GetPartnerConnectionInfo() *_struct.Struct {
	if m != nil {
		return m.PartnerConnectionInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransferConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransferConfig_DestinationDatasetId)(nil),
	}
}

// Represents a data transfer run.
type TransferRun struct {
	// The resource name of the transfer run.
	// Transfer run names have the form
	// `projects/{project_id}/locations/{location}/transferConfigs/{config_id}/runs/{run_id}`.
	// The name is ignored when creating a transfer run.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// User labels.
	Labels map[string]string `protobuf:"bytes,22,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Minimum time after which a transfer run can be started.
	ScheduleTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"`
	// For batch transfer runs, specifies the date and time of the data should be
	// ingested.
	RunTime *timestamp.Timestamp `protobuf:"bytes,10,opt,name=run_time,json=runTime,proto3" json:"run_time,omitempty"`
	// Status of the transfer run.
	ErrorStatus *status.Status `protobuf:"bytes,21,opt,name=error_status,json=errorStatus,proto3" json:"error_status,omitempty"`
	// Output only. Time when transfer run was started.
	// Parameter ignored by server for input requests.
	StartTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Output only. Time when transfer run ended.
	// Parameter ignored by server for input requests.
	EndTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Output only. Last time the data transfer run state was updated.
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Output only. Data transfer specific parameters.
	Params *_struct.Struct `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty"`
	// Data transfer destination.
	//
	// Types that are valid to be assigned to Destination:
	//	*TransferRun_DestinationDatasetId
	Destination isTransferRun_Destination `protobuf_oneof:"destination"`
	// Output only. Data source id.
	DataSourceId string `protobuf:"bytes,7,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	// Data transfer run state. Ignored for input requests.
	State TransferState `protobuf:"varint,8,opt,name=state,proto3,enum=google.cloud.bigquery.datatransfer.v1.TransferState" json:"state,omitempty"`
	// Deprecated. Unique ID of the user on whose behalf transfer is done.
	UserId int64 `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Output only. Describes the schedule of this transfer run if it was
	// created as part of a regular schedule. For batch transfer runs that are
	// scheduled manually, this is empty.
	// NOTE: the system might choose to delay the schedule depending on the
	// current load, so `schedule_time` doesn't always match this.
	Schedule string `protobuf:"bytes,12,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Output only. Pub/Sub topic where a notification will be sent after this
	// transfer run finishes
	NotificationPubsubTopic string `protobuf:"bytes,23,opt,name=notification_pubsub_topic,json=notificationPubsubTopic,proto3" json:"notification_pubsub_topic,omitempty"`
	// Output only. Email notifications will be sent according to these
	// preferences to the email address of the user who owns the transfer config
	// this run was derived from.
	EmailPreferences *EmailPreferences `protobuf:"bytes,25,opt,name=email_preferences,json=emailPreferences,proto3" json:"email_preferences,omitempty"`
	// Output only. This is the same token initialized from TransferConfig.
	// Partner token is a unique identifier used for identifying a transfer setup
	// stored on external partner side. The token is opaque to DTS and can only be
	// interpreted by partner. Partner data source should create a mapping between
	// the config id and the token to validate that a transfer config/run is
	// legitimate.
	PartnerToken         string   `protobuf:"bytes,28,opt,name=partner_token,json=partnerToken,proto3" json:"partner_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRun) Reset()         { *m = TransferRun{} }
func (m *TransferRun) String() string { return proto.CompactTextString(m) }
func (*TransferRun) ProtoMessage()    {}
func (*TransferRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{3}
}

func (m *TransferRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRun.Unmarshal(m, b)
}
func (m *TransferRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRun.Marshal(b, m, deterministic)
}
func (m *TransferRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRun.Merge(m, src)
}
func (m *TransferRun) XXX_Size() int {
	return xxx_messageInfo_TransferRun.Size(m)
}
func (m *TransferRun) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRun.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRun proto.InternalMessageInfo

func (m *TransferRun) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransferRun) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *TransferRun) GetScheduleTime() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduleTime
	}
	return nil
}

func (m *TransferRun) GetRunTime() *timestamp.Timestamp {
	if m != nil {
		return m.RunTime
	}
	return nil
}

func (m *TransferRun) GetErrorStatus() *status.Status {
	if m != nil {
		return m.ErrorStatus
	}
	return nil
}

func (m *TransferRun) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TransferRun) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TransferRun) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *TransferRun) GetParams() *_struct.Struct {
	if m != nil {
		return m.Params
	}
	return nil
}

type isTransferRun_Destination interface {
	isTransferRun_Destination()
}

type TransferRun_DestinationDatasetId struct {
	DestinationDatasetId string `protobuf:"bytes,2,opt,name=destination_dataset_id,json=destinationDatasetId,proto3,oneof"`
}

func (*TransferRun_DestinationDatasetId) isTransferRun_Destination() {}

func (m *TransferRun) GetDestination() isTransferRun_Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *TransferRun) GetDestinationDatasetId() string {
	if x, ok := m.GetDestination().(*TransferRun_DestinationDatasetId); ok {
		return x.DestinationDatasetId
	}
	return ""
}

func (m *TransferRun) GetDataSourceId() string {
	if m != nil {
		return m.DataSourceId
	}
	return ""
}

func (m *TransferRun) GetState() TransferState {
	if m != nil {
		return m.State
	}
	return TransferState_TRANSFER_STATE_UNSPECIFIED
}

func (m *TransferRun) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TransferRun) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func (m *TransferRun) GetNotificationPubsubTopic() string {
	if m != nil {
		return m.NotificationPubsubTopic
	}
	return ""
}

func (m *TransferRun) GetEmailPreferences() *EmailPreferences {
	if m != nil {
		return m.EmailPreferences
	}
	return nil
}

func (m *TransferRun) GetPartnerToken() string {
	if m != nil {
		return m.PartnerToken
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransferRun) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransferRun_DestinationDatasetId)(nil),
	}
}

// Represents a user facing message for a particular data transfer run.
type TransferMessage struct {
	// Time when message was logged.
	MessageTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=message_time,json=messageTime,proto3" json:"message_time,omitempty"`
	// Message severity.
	Severity TransferMessage_MessageSeverity `protobuf:"varint,2,opt,name=severity,proto3,enum=google.cloud.bigquery.datatransfer.v1.TransferMessage_MessageSeverity" json:"severity,omitempty"`
	// Message text.
	MessageText          string   `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferMessage) Reset()         { *m = TransferMessage{} }
func (m *TransferMessage) String() string { return proto.CompactTextString(m) }
func (*TransferMessage) ProtoMessage()    {}
func (*TransferMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c2574420b818ad, []int{4}
}

func (m *TransferMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferMessage.Unmarshal(m, b)
}
func (m *TransferMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferMessage.Marshal(b, m, deterministic)
}
func (m *TransferMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferMessage.Merge(m, src)
}
func (m *TransferMessage) XXX_Size() int {
	return xxx_messageInfo_TransferMessage.Size(m)
}
func (m *TransferMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransferMessage proto.InternalMessageInfo

func (m *TransferMessage) GetMessageTime() *timestamp.Timestamp {
	if m != nil {
		return m.MessageTime
	}
	return nil
}

func (m *TransferMessage) GetSeverity() TransferMessage_MessageSeverity {
	if m != nil {
		return m.Severity
	}
	return TransferMessage_MESSAGE_SEVERITY_UNSPECIFIED
}

func (m *TransferMessage) GetMessageText() string {
	if m != nil {
		return m.MessageText
	}
	return ""
}

func init() {
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.TransferType", TransferType_name, TransferType_value)
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.TransferState", TransferState_name, TransferState_value)
	proto.RegisterEnum("google.cloud.bigquery.datatransfer.v1.TransferMessage_MessageSeverity", TransferMessage_MessageSeverity_name, TransferMessage_MessageSeverity_value)
	proto.RegisterType((*EmailPreferences)(nil), "google.cloud.bigquery.datatransfer.v1.EmailPreferences")
	proto.RegisterType((*ScheduleOptions)(nil), "google.cloud.bigquery.datatransfer.v1.ScheduleOptions")
	proto.RegisterType((*TransferConfig)(nil), "google.cloud.bigquery.datatransfer.v1.TransferConfig")
	proto.RegisterType((*TransferRun)(nil), "google.cloud.bigquery.datatransfer.v1.TransferRun")
	proto.RegisterMapType((map[string]string)(nil), "google.cloud.bigquery.datatransfer.v1.TransferRun.LabelsEntry")
	proto.RegisterType((*TransferMessage)(nil), "google.cloud.bigquery.datatransfer.v1.TransferMessage")
}

func init() {
	proto.RegisterFile("google/cloud/bigquery/datatransfer/v1/transfer.proto", fileDescriptor_90c2574420b818ad)
}

var fileDescriptor_90c2574420b818ad = []byte{
	// 1438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcf, 0x73, 0xd3, 0x46,
	0x14, 0x46, 0x76, 0x9c, 0xc4, 0xcf, 0x76, 0xe2, 0xee, 0x10, 0xac, 0x64, 0x68, 0x49, 0xd3, 0x52,
	0x02, 0x07, 0xa9, 0x49, 0x03, 0x94, 0x30, 0x85, 0xfa, 0x87, 0x12, 0xdc, 0x82, 0x63, 0x64, 0x27,
	0x0c, 0x9d, 0xcc, 0xa8, 0xb2, 0xb5, 0x36, 0x2a, 0xce, 0x4a, 0xdd, 0x95, 0x02, 0x1e, 0x86, 0x7f,
	0xa6, 0x47, 0xee, 0x3d, 0x30, 0xbd, 0xf4, 0xd0, 0x53, 0x2f, 0xfd, 0x17, 0x7a, 0xe6, 0xd6, 0xff,
	0xa0, 0xb3, 0xbb, 0x92, 0xa3, 0x38, 0x90, 0x18, 0xda, 0x53, 0x76, 0xf7, 0xbd, 0xef, 0xf3, 0xdb,
	0xdd, 0x6f, 0xbf, 0xa7, 0xc0, 0x46, 0xdf, 0xf3, 0xfa, 0x03, 0xac, 0x77, 0x07, 0x5e, 0xe8, 0xe8,
	0x1d, 0xb7, 0xff, 0x73, 0x88, 0xe9, 0x50, 0x77, 0xec, 0xc0, 0x0e, 0xa8, 0x4d, 0x58, 0x0f, 0x53,
	0xfd, 0x70, 0x4d, 0x8f, 0xc7, 0x9a, 0x4f, 0xbd, 0xc0, 0x43, 0x97, 0x25, 0x4a, 0x13, 0x28, 0x2d,
	0x46, 0x69, 0x49, 0x94, 0x76, 0xb8, 0xb6, 0x74, 0x29, 0x22, 0xb7, 0x7d, 0x57, 0xef, 0xb9, 0x78,
	0xe0, 0x58, 0x1d, 0xfc, 0xc4, 0x3e, 0x74, 0xbd, 0x88, 0x67, 0x69, 0x31, 0x91, 0x40, 0x31, 0xf3,
	0x42, 0xda, 0xc5, 0x51, 0xe8, 0x62, 0x14, 0x12, 0xb3, 0x4e, 0xd8, 0xd3, 0x59, 0x40, 0xc3, 0x6e,
	0x10, 0x45, 0x2f, 0x8d, 0x47, 0x03, 0xf7, 0x00, 0xb3, 0xc0, 0x3e, 0xf0, 0xa3, 0x84, 0x52, 0x94,
	0x40, 0xfd, 0xae, 0xce, 0x02, 0x3b, 0x08, 0x99, 0x0c, 0xac, 0xd4, 0xa0, 0x68, 0x1c, 0xd8, 0xee,
	0xa0, 0x49, 0x71, 0x0f, 0x53, 0x4c, 0xba, 0x98, 0xa1, 0x2f, 0xe1, 0x3c, 0x26, 0x76, 0x67, 0x80,
	0xad, 0x9e, 0xed, 0x0e, 0x42, 0x8a, 0x2d, 0xcc, 0x53, 0x54, 0x65, 0x59, 0x59, 0x9d, 0x35, 0x91,
	0x8c, 0x6d, 0xc9, 0x90, 0x00, 0xaf, 0xfc, 0xa6, 0xc0, 0x7c, 0xab, 0xfb, 0x04, 0x3b, 0xe1, 0x00,
	0xef, 0xf8, 0x81, 0xeb, 0x11, 0x86, 0x6e, 0x40, 0xc9, 0x71, 0x99, 0xa0, 0xb1, 0xc3, 0xc0, 0xb3,
	0x98, 0x8c, 0xbb, 0xa4, 0xaf, 0xa6, 0x05, 0xd1, 0x42, 0x14, 0x2e, 0x87, 0x81, 0xd7, 0x1a, 0x05,
	0xd1, 0x2d, 0x00, 0x16, 0xd8, 0x34, 0xb0, 0xf8, 0x1e, 0xc4, 0x6f, 0xe6, 0xd6, 0x97, 0xb4, 0xe8,
	0x84, 0xe3, 0x0d, 0x6a, 0xed, 0x78, 0x83, 0x66, 0x56, 0x64, 0xf3, 0x39, 0xba, 0x0e, 0xb3, 0x98,
	0x38, 0x12, 0x98, 0x3a, 0x13, 0x38, 0x83, 0x89, 0xc3, 0x67, 0x2b, 0xaf, 0xb2, 0x30, 0xd7, 0x8e,
	0xee, 0xa9, 0xea, 0x91, 0x9e, 0xdb, 0x47, 0x08, 0xa6, 0x88, 0x1d, 0xfd, 0x7c, 0xd6, 0x14, 0x63,
	0x74, 0x03, 0x2e, 0x38, 0x98, 0x05, 0x2e, 0xb1, 0xf9, 0x06, 0x2d, 0x7e, 0xbb, 0x0c, 0x07, 0x96,
	0xeb, 0x88, 0xdf, 0xca, 0xde, 0x3b, 0x67, 0x9e, 0x4f, 0xc4, 0x6b, 0x32, 0x5c, 0x77, 0xd0, 0xa7,
	0x90, 0x77, 0x5c, 0xe6, 0x0f, 0xec, 0xa1, 0x25, 0x38, 0xd3, 0x82, 0x33, 0x17, 0xad, 0x35, 0x38,
	0xf5, 0xe7, 0x30, 0xc7, 0xe9, 0x2c, 0x79, 0xe5, 0x9c, 0x32, 0x23, 0x92, 0xf2, 0x7c, 0xb5, 0x25,
	0x16, 0xeb, 0x0e, 0xd2, 0x61, 0xda, 0xb7, 0xa9, 0x7d, 0xc0, 0xd4, 0xac, 0xd8, 0x5c, 0xe9, 0xc4,
	0xe6, 0x5a, 0x42, 0x14, 0x66, 0x94, 0x86, 0x96, 0x60, 0x36, 0x3a, 0x75, 0xac, 0xce, 0x08, 0xc2,
	0xd1, 0x1c, 0xd9, 0x50, 0x8c, 0xc7, 0x96, 0x27, 0xaf, 0x4c, 0x55, 0x05, 0xed, 0x0d, 0x6d, 0x22,
	0x39, 0x6b, 0x63, 0x17, 0x6e, 0xce, 0xb3, 0x31, 0x05, 0xdc, 0x04, 0x55, 0xec, 0x8a, 0xe2, 0x1e,
	0xc5, 0xec, 0x89, 0xf5, 0xcc, 0x25, 0x8e, 0xf7, 0xcc, 0x72, 0xec, 0x21, 0x53, 0xf3, 0xcb, 0xca,
	0x6a, 0xc6, 0x5c, 0xe0, 0x71, 0x53, 0x86, 0x1f, 0x89, 0x68, 0xcd, 0x1e, 0x8a, 0xba, 0x23, 0x6d,
	0x38, 0x6a, 0x41, 0x68, 0x65, 0x34, 0x47, 0xdf, 0x42, 0x2e, 0xf4, 0x1d, 0x3b, 0xc0, 0xf2, 0x9a,
	0xa7, 0xce, 0xba, 0xe6, 0x4a, 0xfa, 0xef, 0x72, 0xda, 0x04, 0x89, 0x11, 0x2a, 0xa9, 0x42, 0x81,
	0xe0, 0xe7, 0x81, 0x45, 0x43, 0x22, 0x39, 0x66, 0x27, 0xe3, 0xc8, 0x71, 0x94, 0x19, 0x12, 0x41,
	0xb2, 0x03, 0x19, 0xfe, 0x8e, 0xb0, 0x0a, 0xcb, 0xca, 0xea, 0xdc, 0xfa, 0xc6, 0x84, 0x67, 0x16,
	0xcb, 0xac, 0xc5, 0xb1, 0x92, 0x56, 0xf2, 0xa0, 0x12, 0xcc, 0x84, 0x0c, 0x53, 0x7e, 0xf7, 0xb9,
	0x65, 0x65, 0x35, 0x6d, 0x4e, 0xf3, 0x69, 0xdd, 0x41, 0xd7, 0xa4, 0x36, 0xb8, 0xd4, 0x28, 0xee,
	0xbb, 0x1e, 0x51, 0xe7, 0xf8, 0x55, 0x4a, 0x70, 0x21, 0x0a, 0x99, 0x22, 0x82, 0x36, 0x61, 0x91,
	0x78, 0x81, 0xdb, 0x73, 0xbb, 0x52, 0xa3, 0x7e, 0xd8, 0x61, 0x61, 0xc7, 0x0a, 0x3c, 0xdf, 0xed,
	0xaa, 0xf3, 0x42, 0x01, 0xa5, 0x64, 0x42, 0x53, 0xc4, 0xdb, 0x3c, 0x8c, 0x1c, 0xf8, 0x48, 0x3c,
	0x73, 0xcb, 0x3f, 0xb2, 0x02, 0x15, 0x89, 0xa3, 0xb9, 0x39, 0xe1, 0xee, 0xc6, 0x9d, 0xc4, 0x2c,
	0xe2, 0x71, 0x6f, 0xf9, 0x0c, 0x0a, 0xbe, 0x4d, 0x03, 0x82, 0xa9, 0x15, 0x78, 0x4f, 0x31, 0x51,
	0x2f, 0x48, 0xa1, 0x47, 0x8b, 0x6d, 0xbe, 0x86, 0x76, 0xa0, 0x14, 0x27, 0x75, 0x3d, 0x42, 0x70,
	0x57, 0x6c, 0xc6, 0x25, 0x3d, 0x4f, 0x2d, 0x9d, 0xae, 0xfc, 0x85, 0x08, 0x57, 0x1d, 0xc1, 0xea,
	0xa4, 0xe7, 0x6d, 0xbe, 0x56, 0xde, 0x94, 0x7f, 0x55, 0x60, 0x3d, 0xae, 0xfc, 0x58, 0xe1, 0x92,
	0xca, 0xf6, 0x5d, 0xa6, 0x75, 0xbd, 0x03, 0x7d, 0xcc, 0x09, 0x36, 0x7c, 0xea, 0xfd, 0x84, 0xbb,
	0x01, 0xd3, 0x5f, 0x44, 0xa3, 0x97, 0x23, 0xfb, 0x97, 0x29, 0x4c, 0x7f, 0x11, 0x2f, 0xf0, 0x72,
	0x7b, 0x6e, 0xff, 0x25, 0xaa, 0xbf, 0x05, 0x35, 0xf0, 0xe4, 0xa1, 0x33, 0xfd, 0x45, 0x3c, 0x9c,
	0x80, 0xaa, 0x52, 0x80, 0x5c, 0xc2, 0x56, 0x56, 0xfe, 0xc9, 0x42, 0x2e, 0x2e, 0xd1, 0x0c, 0xc9,
	0x5b, 0x9d, 0x6a, 0x0f, 0xa6, 0x07, 0x76, 0x07, 0x0f, 0x98, 0x7a, 0x61, 0x39, 0xbd, 0x9a, 0x5b,
	0xbf, 0xf3, 0x9e, 0xea, 0x34, 0x43, 0xa2, 0xdd, 0x17, 0x04, 0x06, 0x09, 0xe8, 0xd0, 0x8c, 0xd8,
	0xd0, 0x5d, 0x28, 0x8c, 0x3c, 0x43, 0xbc, 0x9c, 0xf4, 0x99, 0x26, 0x9b, 0x8f, 0x01, 0xb1, 0x41,
	0x8f, 0x5e, 0x1d, 0x9c, 0x6d, 0xd0, 0x34, 0x7a, 0x6c, 0xd7, 0x21, 0x8f, 0x29, 0xf5, 0xa8, 0x25,
	0x5b, 0x97, 0xba, 0x20, 0xa0, 0x28, 0x86, 0x52, 0xbf, 0xab, 0xb5, 0x44, 0xc4, 0xcc, 0x89, 0x3c,
	0x39, 0x41, 0x77, 0x8e, 0x75, 0x92, 0x09, 0x9d, 0x22, 0xd1, 0x4e, 0x36, 0x13, 0xed, 0x24, 0x33,
	0x19, 0x3a, 0xee, 0x29, 0xe3, 0x36, 0x35, 0xfd, 0xfe, 0x36, 0xb5, 0x31, 0xa1, 0xdb, 0x4b, 0x64,
	0x6c, 0xf9, 0xb7, 0x4f, 0x6f, 0x52, 0x22, 0xf9, 0x9d, 0x9d, 0xea, 0xea, 0x89, 0x36, 0x34, 0x73,
	0x64, 0x35, 0xc7, 0x7b, 0xd1, 0x77, 0xb1, 0xff, 0xcd, 0x7e, 0xb8, 0xff, 0x9d, 0x69, 0x7d, 0x97,
	0x12, 0xfd, 0x2b, 0x7f, 0x54, 0xc9, 0x51, 0x13, 0xbb, 0x7b, 0x9a, 0xdf, 0x95, 0x8e, 0x10, 0xef,
	0x34, 0x3d, 0xf7, 0x6d, 0xa6, 0xb7, 0xf8, 0x9f, 0x4c, 0x4f, 0xfe, 0xe2, 0x49, 0xe7, 0x5b, 0x1d,
	0x77, 0xbe, 0x8b, 0x89, 0xb3, 0x4d, 0xda, 0xdf, 0xd2, 0x2d, 0xc8, 0x25, 0x5e, 0x1f, 0x2a, 0x42,
	0xfa, 0x29, 0x1e, 0x46, 0x0f, 0x9c, 0x0f, 0xd1, 0x79, 0xc8, 0x1c, 0xda, 0x83, 0x50, 0x7e, 0xe4,
	0x64, 0x4d, 0x39, 0xd9, 0x4c, 0x7d, 0xad, 0x6c, 0xfe, 0xa1, 0xbc, 0x29, 0xff, 0xae, 0xc0, 0x95,
	0x49, 0x8c, 0x8e, 0xbb, 0xc7, 0xdd, 0x0f, 0x71, 0x37, 0x9d, 0x86, 0xdc, 0xc4, 0x68, 0x48, 0x5e,
	0xa2, 0xf6, 0xff, 0x66, 0x74, 0x09, 0xd6, 0x71, 0xcf, 0x7b, 0x9d, 0x82, 0xf9, 0x58, 0x39, 0x0f,
	0x30, 0x63, 0x76, 0x1f, 0xa3, 0x6f, 0x20, 0x7f, 0x20, 0x87, 0x93, 0x7e, 0x28, 0xe6, 0xa2, 0x7c,
	0xf1, 0xba, 0x3a, 0x30, 0xcb, 0xf0, 0x21, 0xa6, 0x6e, 0x30, 0x14, 0xa7, 0x38, 0xb7, 0xbe, 0xf5,
	0x9e, 0x12, 0x8e, 0x0a, 0xd1, 0xa2, 0xbf, 0xad, 0x88, 0xcd, 0x1c, 0xf1, 0xf2, 0x0f, 0xbf, 0x51,
	0x89, 0xf8, 0x79, 0x10, 0x7f, 0xf8, 0xc5, 0x65, 0xe0, 0xe7, 0xc1, 0xca, 0x8f, 0x30, 0x3f, 0x86,
	0x47, 0xcb, 0x70, 0xf1, 0x81, 0xd1, 0x6a, 0x95, 0xb7, 0x0d, 0xab, 0x65, 0xec, 0x19, 0x66, 0xbd,
	0xfd, 0xd8, 0xda, 0x6d, 0xb4, 0x9a, 0x46, 0xb5, 0xbe, 0x55, 0x37, 0x6a, 0xc5, 0x73, 0x68, 0x16,
	0xa6, 0xea, 0x8d, 0xad, 0x9d, 0xa2, 0x82, 0x72, 0x30, 0xf3, 0xa8, 0x6c, 0x36, 0xea, 0x8d, 0xed,
	0x62, 0x0a, 0x65, 0x21, 0x63, 0x98, 0xe6, 0x8e, 0x59, 0x4c, 0xf3, 0x61, 0xcd, 0xa8, 0xec, 0x6e,
	0x17, 0xa7, 0xae, 0x7d, 0x0f, 0xf9, 0xb8, 0xe2, 0xf6, 0xd0, 0xc7, 0xe8, 0x63, 0x58, 0x6c, 0x9b,
	0xe5, 0x46, 0x6b, 0xcb, 0x30, 0xad, 0xf6, 0xe3, 0xa6, 0x31, 0xc6, 0x9d, 0x85, 0x4c, 0xa5, 0xdc,
	0xae, 0xde, 0x2b, 0x2a, 0xa8, 0x00, 0xd9, 0x56, 0xdb, 0x34, 0xca, 0x0f, 0x04, 0xfd, 0x52, 0x4a,
	0x55, 0xae, 0x31, 0x28, 0x1c, 0x7b, 0xc1, 0xe8, 0x13, 0x58, 0x1a, 0xb1, 0xb5, 0xda, 0xe5, 0xf6,
	0x38, 0x5d, 0x0e, 0x66, 0x9a, 0x46, 0xa3, 0x26, 0x0b, 0xcc, 0xc1, 0x8c, 0xb9, 0xdb, 0x10, 0xd5,
	0xa6, 0x05, 0xfb, 0x6e, 0xb5, 0x6a, 0x18, 0x35, 0xa3, 0x56, 0x9c, 0x42, 0x00, 0xd3, 0x5b, 0xe5,
	0xfa, 0x7d, 0xa3, 0x56, 0xcc, 0xf0, 0x50, 0xb5, 0xdc, 0xa8, 0x1a, 0xf7, 0xf9, 0x74, 0xba, 0xf2,
	0x57, 0xea, 0x4d, 0x19, 0xc3, 0x17, 0xa7, 0x48, 0x5a, 0xc8, 0xb9, 0x69, 0x53, 0x4c, 0x02, 0x84,
	0x4e, 0x0a, 0x12, 0x5d, 0x99, 0x50, 0xa4, 0x70, 0xb5, 0xeb, 0x1d, 0x4c, 0x26, 0x83, 0xca, 0xe8,
	0x20, 0x9a, 0x5c, 0x69, 0x4d, 0xe5, 0x87, 0x87, 0x11, 0xae, 0xef, 0x0d, 0x6c, 0xd2, 0xd7, 0x3c,
	0xda, 0xd7, 0xfb, 0x98, 0x08, 0x1d, 0xea, 0x47, 0x2f, 0xef, 0x8c, 0xff, 0x2c, 0x6f, 0x27, 0xe7,
	0xbf, 0xa4, 0x32, 0xdb, 0xd5, 0x4a, 0xad, 0xfd, 0x2a, 0x75, 0x79, 0x5b, 0x72, 0x57, 0x45, 0x4d,
	0x15, 0xb7, 0xff, 0x50, 0xd4, 0xc4, 0x9d, 0x3b, 0x2e, 0x43, 0xdb, 0x5b, 0xfb, 0x33, 0xce, 0xdb,
	0x17, 0x79, 0xfb, 0x71, 0xde, 0x7e, 0x32, 0x6f, 0x7f, 0x6f, 0xad, 0x33, 0x2d, 0xaa, 0xfa, 0xea,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x0e, 0xfd, 0xb7, 0xee, 0x0e, 0x00, 0x00,
}
